package presence

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/grokify/go-ringcentral/models"
)

// GetRestapiV10AccountAccountIDExtensionExtensionIDPresenceReader is a Reader for the GetRestapiV10AccountAccountIDExtensionExtensionIDPresence structure.
type GetRestapiV10AccountAccountIDExtensionExtensionIDPresenceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDPresenceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {

	result := NewGetRestapiV10AccountAccountIDExtensionExtensionIDPresenceDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result

}

// NewGetRestapiV10AccountAccountIDExtensionExtensionIDPresenceDefault creates a GetRestapiV10AccountAccountIDExtensionExtensionIDPresenceDefault with default headers values
func NewGetRestapiV10AccountAccountIDExtensionExtensionIDPresenceDefault(code int) *GetRestapiV10AccountAccountIDExtensionExtensionIDPresenceDefault {
	return &GetRestapiV10AccountAccountIDExtensionExtensionIDPresenceDefault{
		_statusCode: code,
	}
}

/*GetRestapiV10AccountAccountIDExtensionExtensionIDPresenceDefault handles this case with default header values.

OK
*/
type GetRestapiV10AccountAccountIDExtensionExtensionIDPresenceDefault struct {
	_statusCode int

	Payload *models.PresenceInfo
}

// Code gets the status code for the get restapi v10 account account ID extension extension ID presence default response
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDPresenceDefault) Code() int {
	return o._statusCode
}

func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDPresenceDefault) Error() string {
	return fmt.Sprintf("[GET /restapi/v1.0/account/{accountId}/extension/{extensionId}/presence][%d] GetRestapiV10AccountAccountIDExtensionExtensionIDPresence default  %+v", o._statusCode, o.Payload)
}

func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDPresenceDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PresenceInfo)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
