package ring_out

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetRestapiV10AccountAccountIDExtensionExtensionIDRingoutRingoutIDParams creates a new GetRestapiV10AccountAccountIDExtensionExtensionIDRingoutRingoutIDParams object
// with the default values initialized.
func NewGetRestapiV10AccountAccountIDExtensionExtensionIDRingoutRingoutIDParams() *GetRestapiV10AccountAccountIDExtensionExtensionIDRingoutRingoutIDParams {
	var (
		accountIDDefault   = string("~")
		extensionIDDefault = string("~")
	)
	return &GetRestapiV10AccountAccountIDExtensionExtensionIDRingoutRingoutIDParams{
		AccountID:   accountIDDefault,
		ExtensionID: extensionIDDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetRestapiV10AccountAccountIDExtensionExtensionIDRingoutRingoutIDParamsWithTimeout creates a new GetRestapiV10AccountAccountIDExtensionExtensionIDRingoutRingoutIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetRestapiV10AccountAccountIDExtensionExtensionIDRingoutRingoutIDParamsWithTimeout(timeout time.Duration) *GetRestapiV10AccountAccountIDExtensionExtensionIDRingoutRingoutIDParams {
	var (
		accountIDDefault   = string("~")
		extensionIDDefault = string("~")
	)
	return &GetRestapiV10AccountAccountIDExtensionExtensionIDRingoutRingoutIDParams{
		AccountID:   accountIDDefault,
		ExtensionID: extensionIDDefault,

		timeout: timeout,
	}
}

// NewGetRestapiV10AccountAccountIDExtensionExtensionIDRingoutRingoutIDParamsWithContext creates a new GetRestapiV10AccountAccountIDExtensionExtensionIDRingoutRingoutIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetRestapiV10AccountAccountIDExtensionExtensionIDRingoutRingoutIDParamsWithContext(ctx context.Context) *GetRestapiV10AccountAccountIDExtensionExtensionIDRingoutRingoutIDParams {
	var (
		accountIdDefault   = string("~")
		extensionIdDefault = string("~")
	)
	return &GetRestapiV10AccountAccountIDExtensionExtensionIDRingoutRingoutIDParams{
		AccountID:   accountIdDefault,
		ExtensionID: extensionIdDefault,

		Context: ctx,
	}
}

// NewGetRestapiV10AccountAccountIDExtensionExtensionIDRingoutRingoutIDParamsWithHTTPClient creates a new GetRestapiV10AccountAccountIDExtensionExtensionIDRingoutRingoutIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetRestapiV10AccountAccountIDExtensionExtensionIDRingoutRingoutIDParamsWithHTTPClient(client *http.Client) *GetRestapiV10AccountAccountIDExtensionExtensionIDRingoutRingoutIDParams {
	var (
		accountIdDefault   = string("~")
		extensionIdDefault = string("~")
	)
	return &GetRestapiV10AccountAccountIDExtensionExtensionIDRingoutRingoutIDParams{
		AccountID:   accountIdDefault,
		ExtensionID: extensionIdDefault,
		HTTPClient:  client,
	}
}

/*GetRestapiV10AccountAccountIDExtensionExtensionIDRingoutRingoutIDParams contains all the parameters to send to the API endpoint
for the get restapi v10 account account ID extension extension ID ringout ringout ID operation typically these are written to a http.Request
*/
type GetRestapiV10AccountAccountIDExtensionExtensionIDRingoutRingoutIDParams struct {

	/*AccountID
	  Internal identifier of a RingCentral account or tilde (~) to indicate the account logged-in within the current session

	*/
	AccountID string
	/*ExtensionID
	  Internal identifier of an extension or tilde (~) to indicate the extension assigned to the account logged-in within the current session

	*/
	ExtensionID string
	/*RingoutID
	  Internal identifier of a RingOut call

	*/
	RingoutID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get restapi v10 account account ID extension extension ID ringout ringout ID params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDRingoutRingoutIDParams) WithTimeout(timeout time.Duration) *GetRestapiV10AccountAccountIDExtensionExtensionIDRingoutRingoutIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get restapi v10 account account ID extension extension ID ringout ringout ID params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDRingoutRingoutIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get restapi v10 account account ID extension extension ID ringout ringout ID params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDRingoutRingoutIDParams) WithContext(ctx context.Context) *GetRestapiV10AccountAccountIDExtensionExtensionIDRingoutRingoutIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get restapi v10 account account ID extension extension ID ringout ringout ID params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDRingoutRingoutIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get restapi v10 account account ID extension extension ID ringout ringout ID params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDRingoutRingoutIDParams) WithHTTPClient(client *http.Client) *GetRestapiV10AccountAccountIDExtensionExtensionIDRingoutRingoutIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get restapi v10 account account ID extension extension ID ringout ringout ID params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDRingoutRingoutIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccountID adds the accountID to the get restapi v10 account account ID extension extension ID ringout ringout ID params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDRingoutRingoutIDParams) WithAccountID(accountID string) *GetRestapiV10AccountAccountIDExtensionExtensionIDRingoutRingoutIDParams {
	o.SetAccountID(accountID)
	return o
}

// SetAccountID adds the accountId to the get restapi v10 account account ID extension extension ID ringout ringout ID params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDRingoutRingoutIDParams) SetAccountID(accountID string) {
	o.AccountID = accountID
}

// WithExtensionID adds the extensionID to the get restapi v10 account account ID extension extension ID ringout ringout ID params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDRingoutRingoutIDParams) WithExtensionID(extensionID string) *GetRestapiV10AccountAccountIDExtensionExtensionIDRingoutRingoutIDParams {
	o.SetExtensionID(extensionID)
	return o
}

// SetExtensionID adds the extensionId to the get restapi v10 account account ID extension extension ID ringout ringout ID params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDRingoutRingoutIDParams) SetExtensionID(extensionID string) {
	o.ExtensionID = extensionID
}

// WithRingoutID adds the ringoutID to the get restapi v10 account account ID extension extension ID ringout ringout ID params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDRingoutRingoutIDParams) WithRingoutID(ringoutID string) *GetRestapiV10AccountAccountIDExtensionExtensionIDRingoutRingoutIDParams {
	o.SetRingoutID(ringoutID)
	return o
}

// SetRingoutID adds the ringoutId to the get restapi v10 account account ID extension extension ID ringout ringout ID params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDRingoutRingoutIDParams) SetRingoutID(ringoutID string) {
	o.RingoutID = ringoutID
}

// WriteToRequest writes these params to a swagger request
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDRingoutRingoutIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param accountId
	if err := r.SetPathParam("accountId", o.AccountID); err != nil {
		return err
	}

	// path param extensionId
	if err := r.SetPathParam("extensionId", o.ExtensionID); err != nil {
		return err
	}

	// path param ringoutId
	if err := r.SetPathParam("ringoutId", o.RingoutID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
