package ring_out

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/grokify/go-ringcentral/models"
)

// GetRestapiV10AccountAccountIDExtensionExtensionIDRingoutRingoutIDReader is a Reader for the GetRestapiV10AccountAccountIDExtensionExtensionIDRingoutRingoutID structure.
type GetRestapiV10AccountAccountIDExtensionExtensionIDRingoutRingoutIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDRingoutRingoutIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {

	result := NewGetRestapiV10AccountAccountIDExtensionExtensionIDRingoutRingoutIDDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result

}

// NewGetRestapiV10AccountAccountIDExtensionExtensionIDRingoutRingoutIDDefault creates a GetRestapiV10AccountAccountIDExtensionExtensionIDRingoutRingoutIDDefault with default headers values
func NewGetRestapiV10AccountAccountIDExtensionExtensionIDRingoutRingoutIDDefault(code int) *GetRestapiV10AccountAccountIDExtensionExtensionIDRingoutRingoutIDDefault {
	return &GetRestapiV10AccountAccountIDExtensionExtensionIDRingoutRingoutIDDefault{
		_statusCode: code,
	}
}

/*GetRestapiV10AccountAccountIDExtensionExtensionIDRingoutRingoutIDDefault handles this case with default header values.

OK
*/
type GetRestapiV10AccountAccountIDExtensionExtensionIDRingoutRingoutIDDefault struct {
	_statusCode int

	Payload *models.RingOutInfo
}

// Code gets the status code for the get restapi v10 account account ID extension extension ID ringout ringout ID default response
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDRingoutRingoutIDDefault) Code() int {
	return o._statusCode
}

func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDRingoutRingoutIDDefault) Error() string {
	return fmt.Sprintf("[GET /restapi/v1.0/account/{accountId}/extension/{extensionId}/ringout/{ringoutId}][%d] GetRestapiV10AccountAccountIDExtensionExtensionIDRingoutRingoutID default  %+v", o._statusCode, o.Payload)
}

func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDRingoutRingoutIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RingOutInfo)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
