package authorization_profile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetRestapiV10AccountAccountIDExtensionExtensionIDAuthzProfileCheckParams creates a new GetRestapiV10AccountAccountIDExtensionExtensionIDAuthzProfileCheckParams object
// with the default values initialized.
func NewGetRestapiV10AccountAccountIDExtensionExtensionIDAuthzProfileCheckParams() *GetRestapiV10AccountAccountIDExtensionExtensionIDAuthzProfileCheckParams {
	var (
		accountIDDefault   = string("~")
		extensionIDDefault = string("~")
	)
	return &GetRestapiV10AccountAccountIDExtensionExtensionIDAuthzProfileCheckParams{
		AccountID:   accountIDDefault,
		ExtensionID: extensionIDDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetRestapiV10AccountAccountIDExtensionExtensionIDAuthzProfileCheckParamsWithTimeout creates a new GetRestapiV10AccountAccountIDExtensionExtensionIDAuthzProfileCheckParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetRestapiV10AccountAccountIDExtensionExtensionIDAuthzProfileCheckParamsWithTimeout(timeout time.Duration) *GetRestapiV10AccountAccountIDExtensionExtensionIDAuthzProfileCheckParams {
	var (
		accountIDDefault   = string("~")
		extensionIDDefault = string("~")
	)
	return &GetRestapiV10AccountAccountIDExtensionExtensionIDAuthzProfileCheckParams{
		AccountID:   accountIDDefault,
		ExtensionID: extensionIDDefault,

		timeout: timeout,
	}
}

// NewGetRestapiV10AccountAccountIDExtensionExtensionIDAuthzProfileCheckParamsWithContext creates a new GetRestapiV10AccountAccountIDExtensionExtensionIDAuthzProfileCheckParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetRestapiV10AccountAccountIDExtensionExtensionIDAuthzProfileCheckParamsWithContext(ctx context.Context) *GetRestapiV10AccountAccountIDExtensionExtensionIDAuthzProfileCheckParams {
	var (
		accountIdDefault   = string("~")
		extensionIdDefault = string("~")
	)
	return &GetRestapiV10AccountAccountIDExtensionExtensionIDAuthzProfileCheckParams{
		AccountID:   accountIdDefault,
		ExtensionID: extensionIdDefault,

		Context: ctx,
	}
}

// NewGetRestapiV10AccountAccountIDExtensionExtensionIDAuthzProfileCheckParamsWithHTTPClient creates a new GetRestapiV10AccountAccountIDExtensionExtensionIDAuthzProfileCheckParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetRestapiV10AccountAccountIDExtensionExtensionIDAuthzProfileCheckParamsWithHTTPClient(client *http.Client) *GetRestapiV10AccountAccountIDExtensionExtensionIDAuthzProfileCheckParams {
	var (
		accountIdDefault   = string("~")
		extensionIdDefault = string("~")
	)
	return &GetRestapiV10AccountAccountIDExtensionExtensionIDAuthzProfileCheckParams{
		AccountID:   accountIdDefault,
		ExtensionID: extensionIdDefault,
		HTTPClient:  client,
	}
}

/*GetRestapiV10AccountAccountIDExtensionExtensionIDAuthzProfileCheckParams contains all the parameters to send to the API endpoint
for the get restapi v10 account account ID extension extension ID authz profile check operation typically these are written to a http.Request
*/
type GetRestapiV10AccountAccountIDExtensionExtensionIDAuthzProfileCheckParams struct {

	/*AccountID
	  Internal identifier of a RingCentral account or tilde (~) to indicate the account logged-in within the current session

	*/
	AccountID string
	/*ExtensionID
	  Internal identifier of an extension or tilde (~) to indicate the extension assigned to the account logged-in within the current session

	*/
	ExtensionID string
	/*PermissionID
	  Permission to check

	*/
	PermissionID *string
	/*TargetExtensionID
	  Optional. Internal identifier of an extension for which user permissions are to be checked. The default value is the currently logged-in extension

	*/
	TargetExtensionID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get restapi v10 account account ID extension extension ID authz profile check params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDAuthzProfileCheckParams) WithTimeout(timeout time.Duration) *GetRestapiV10AccountAccountIDExtensionExtensionIDAuthzProfileCheckParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get restapi v10 account account ID extension extension ID authz profile check params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDAuthzProfileCheckParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get restapi v10 account account ID extension extension ID authz profile check params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDAuthzProfileCheckParams) WithContext(ctx context.Context) *GetRestapiV10AccountAccountIDExtensionExtensionIDAuthzProfileCheckParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get restapi v10 account account ID extension extension ID authz profile check params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDAuthzProfileCheckParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get restapi v10 account account ID extension extension ID authz profile check params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDAuthzProfileCheckParams) WithHTTPClient(client *http.Client) *GetRestapiV10AccountAccountIDExtensionExtensionIDAuthzProfileCheckParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get restapi v10 account account ID extension extension ID authz profile check params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDAuthzProfileCheckParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccountID adds the accountID to the get restapi v10 account account ID extension extension ID authz profile check params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDAuthzProfileCheckParams) WithAccountID(accountID string) *GetRestapiV10AccountAccountIDExtensionExtensionIDAuthzProfileCheckParams {
	o.SetAccountID(accountID)
	return o
}

// SetAccountID adds the accountId to the get restapi v10 account account ID extension extension ID authz profile check params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDAuthzProfileCheckParams) SetAccountID(accountID string) {
	o.AccountID = accountID
}

// WithExtensionID adds the extensionID to the get restapi v10 account account ID extension extension ID authz profile check params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDAuthzProfileCheckParams) WithExtensionID(extensionID string) *GetRestapiV10AccountAccountIDExtensionExtensionIDAuthzProfileCheckParams {
	o.SetExtensionID(extensionID)
	return o
}

// SetExtensionID adds the extensionId to the get restapi v10 account account ID extension extension ID authz profile check params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDAuthzProfileCheckParams) SetExtensionID(extensionID string) {
	o.ExtensionID = extensionID
}

// WithPermissionID adds the permissionID to the get restapi v10 account account ID extension extension ID authz profile check params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDAuthzProfileCheckParams) WithPermissionID(permissionID *string) *GetRestapiV10AccountAccountIDExtensionExtensionIDAuthzProfileCheckParams {
	o.SetPermissionID(permissionID)
	return o
}

// SetPermissionID adds the permissionId to the get restapi v10 account account ID extension extension ID authz profile check params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDAuthzProfileCheckParams) SetPermissionID(permissionID *string) {
	o.PermissionID = permissionID
}

// WithTargetExtensionID adds the targetExtensionID to the get restapi v10 account account ID extension extension ID authz profile check params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDAuthzProfileCheckParams) WithTargetExtensionID(targetExtensionID *string) *GetRestapiV10AccountAccountIDExtensionExtensionIDAuthzProfileCheckParams {
	o.SetTargetExtensionID(targetExtensionID)
	return o
}

// SetTargetExtensionID adds the targetExtensionId to the get restapi v10 account account ID extension extension ID authz profile check params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDAuthzProfileCheckParams) SetTargetExtensionID(targetExtensionID *string) {
	o.TargetExtensionID = targetExtensionID
}

// WriteToRequest writes these params to a swagger request
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDAuthzProfileCheckParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param accountId
	if err := r.SetPathParam("accountId", o.AccountID); err != nil {
		return err
	}

	// path param extensionId
	if err := r.SetPathParam("extensionId", o.ExtensionID); err != nil {
		return err
	}

	if o.PermissionID != nil {

		// query param permissionId
		var qrPermissionID string
		if o.PermissionID != nil {
			qrPermissionID = *o.PermissionID
		}
		qPermissionID := qrPermissionID
		if qPermissionID != "" {
			if err := r.SetQueryParam("permissionId", qPermissionID); err != nil {
				return err
			}
		}

	}

	if o.TargetExtensionID != nil {

		// query param targetExtensionId
		var qrTargetExtensionID string
		if o.TargetExtensionID != nil {
			qrTargetExtensionID = *o.TargetExtensionID
		}
		qTargetExtensionID := qrTargetExtensionID
		if qTargetExtensionID != "" {
			if err := r.SetQueryParam("targetExtensionId", qTargetExtensionID); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
