package authorization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostRestapiOauthAuthorizeParams creates a new PostRestapiOauthAuthorizeParams object
// with the default values initialized.
func NewPostRestapiOauthAuthorizeParams() *PostRestapiOauthAuthorizeParams {
	var ()
	return &PostRestapiOauthAuthorizeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostRestapiOauthAuthorizeParamsWithTimeout creates a new PostRestapiOauthAuthorizeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostRestapiOauthAuthorizeParamsWithTimeout(timeout time.Duration) *PostRestapiOauthAuthorizeParams {
	var ()
	return &PostRestapiOauthAuthorizeParams{

		timeout: timeout,
	}
}

// NewPostRestapiOauthAuthorizeParamsWithContext creates a new PostRestapiOauthAuthorizeParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostRestapiOauthAuthorizeParamsWithContext(ctx context.Context) *PostRestapiOauthAuthorizeParams {
	var ()
	return &PostRestapiOauthAuthorizeParams{

		Context: ctx,
	}
}

// NewPostRestapiOauthAuthorizeParamsWithHTTPClient creates a new PostRestapiOauthAuthorizeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostRestapiOauthAuthorizeParamsWithHTTPClient(client *http.Client) *PostRestapiOauthAuthorizeParams {
	var ()
	return &PostRestapiOauthAuthorizeParams{
		HTTPClient: client,
	}
}

/*PostRestapiOauthAuthorizeParams contains all the parameters to send to the API endpoint
for the post restapi oauth authorize operation typically these are written to a http.Request
*/
type PostRestapiOauthAuthorizeParams struct {

	/*Body*/
	Body PostRestapiOauthAuthorizeBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post restapi oauth authorize params
func (o *PostRestapiOauthAuthorizeParams) WithTimeout(timeout time.Duration) *PostRestapiOauthAuthorizeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post restapi oauth authorize params
func (o *PostRestapiOauthAuthorizeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post restapi oauth authorize params
func (o *PostRestapiOauthAuthorizeParams) WithContext(ctx context.Context) *PostRestapiOauthAuthorizeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post restapi oauth authorize params
func (o *PostRestapiOauthAuthorizeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post restapi oauth authorize params
func (o *PostRestapiOauthAuthorizeParams) WithHTTPClient(client *http.Client) *PostRestapiOauthAuthorizeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post restapi oauth authorize params
func (o *PostRestapiOauthAuthorizeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post restapi oauth authorize params
func (o *PostRestapiOauthAuthorizeParams) WithBody(body PostRestapiOauthAuthorizeBody) *PostRestapiOauthAuthorizeParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post restapi oauth authorize params
func (o *PostRestapiOauthAuthorizeParams) SetBody(body PostRestapiOauthAuthorizeBody) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostRestapiOauthAuthorizeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
