package address_book

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteRestapiV10AccountAccountIDExtensionExtensionIDAddressBookContactContactIDReader is a Reader for the DeleteRestapiV10AccountAccountIDExtensionExtensionIDAddressBookContactContactID structure.
type DeleteRestapiV10AccountAccountIDExtensionExtensionIDAddressBookContactContactIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteRestapiV10AccountAccountIDExtensionExtensionIDAddressBookContactContactIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {

	result := NewDeleteRestapiV10AccountAccountIDExtensionExtensionIDAddressBookContactContactIDDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result

}

// NewDeleteRestapiV10AccountAccountIDExtensionExtensionIDAddressBookContactContactIDDefault creates a DeleteRestapiV10AccountAccountIDExtensionExtensionIDAddressBookContactContactIDDefault with default headers values
func NewDeleteRestapiV10AccountAccountIDExtensionExtensionIDAddressBookContactContactIDDefault(code int) *DeleteRestapiV10AccountAccountIDExtensionExtensionIDAddressBookContactContactIDDefault {
	return &DeleteRestapiV10AccountAccountIDExtensionExtensionIDAddressBookContactContactIDDefault{
		_statusCode: code,
	}
}

/*DeleteRestapiV10AccountAccountIDExtensionExtensionIDAddressBookContactContactIDDefault handles this case with default header values.

OK
*/
type DeleteRestapiV10AccountAccountIDExtensionExtensionIDAddressBookContactContactIDDefault struct {
	_statusCode int
}

// Code gets the status code for the delete restapi v10 account account ID extension extension ID address book contact contact ID default response
func (o *DeleteRestapiV10AccountAccountIDExtensionExtensionIDAddressBookContactContactIDDefault) Code() int {
	return o._statusCode
}

func (o *DeleteRestapiV10AccountAccountIDExtensionExtensionIDAddressBookContactContactIDDefault) Error() string {
	return fmt.Sprintf("[DELETE /restapi/v1.0/account/{accountId}/extension/{extensionId}/address-book/contact/{contactId}][%d] DeleteRestapiV10AccountAccountIDExtensionExtensionIDAddressBookContactContactID default ", o._statusCode)
}

func (o *DeleteRestapiV10AccountAccountIDExtensionExtensionIDAddressBookContactContactIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
