package address_book

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/grokify/go-ringcentral/models"
)

// GetRestapiV10AccountAccountIDExtensionExtensionIDAddressBookSyncReader is a Reader for the GetRestapiV10AccountAccountIDExtensionExtensionIDAddressBookSync structure.
type GetRestapiV10AccountAccountIDExtensionExtensionIDAddressBookSyncReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDAddressBookSyncReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {

	result := NewGetRestapiV10AccountAccountIDExtensionExtensionIDAddressBookSyncDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result

}

// NewGetRestapiV10AccountAccountIDExtensionExtensionIDAddressBookSyncDefault creates a GetRestapiV10AccountAccountIDExtensionExtensionIDAddressBookSyncDefault with default headers values
func NewGetRestapiV10AccountAccountIDExtensionExtensionIDAddressBookSyncDefault(code int) *GetRestapiV10AccountAccountIDExtensionExtensionIDAddressBookSyncDefault {
	return &GetRestapiV10AccountAccountIDExtensionExtensionIDAddressBookSyncDefault{
		_statusCode: code,
	}
}

/*GetRestapiV10AccountAccountIDExtensionExtensionIDAddressBookSyncDefault handles this case with default header values.

OK
*/
type GetRestapiV10AccountAccountIDExtensionExtensionIDAddressBookSyncDefault struct {
	_statusCode int

	Payload GetRestapiV10AccountAccountIDExtensionExtensionIDAddressBookSyncDefaultBody
}

// Code gets the status code for the get restapi v10 account account ID extension extension ID address book sync default response
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDAddressBookSyncDefault) Code() int {
	return o._statusCode
}

func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDAddressBookSyncDefault) Error() string {
	return fmt.Sprintf("[GET /restapi/v1.0/account/{accountId}/extension/{extensionId}/address-book-sync][%d] GetRestapiV10AccountAccountIDExtensionExtensionIDAddressBookSync default  %+v", o._statusCode, o.Payload)
}

func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDAddressBookSyncDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetRestapiV10AccountAccountIDExtensionExtensionIDAddressBookSyncDefaultBody get restapi v10 account account ID extension extension ID address book sync default body
swagger:model GetRestapiV10AccountAccountIDExtensionExtensionIDAddressBookSyncDefaultBody
*/
type GetRestapiV10AccountAccountIDExtensionExtensionIDAddressBookSyncDefaultBody struct {

	// Internal identifier of the next page, if any
	// Required: true
	NextPageID *int64 `json:"nextPageId"`

	// URL of the next page, if any
	// Required: true
	NextPageURI *string `json:"nextPageUri"`

	// List of contacts with synchronization information
	// Required: true
	Records []*models.PersonalContactInfo `json:"records"`

	// Sync type, token and time
	// Required: true
	SyncInfo *models.SyncInfo `json:"syncInfo"`
}

// Validate validates this get restapi v10 account account ID extension extension ID address book sync default body
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDAddressBookSyncDefaultBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateNextPageID(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := o.validateNextPageURI(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := o.validateRecords(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := o.validateSyncInfo(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDAddressBookSyncDefaultBody) validateNextPageID(formats strfmt.Registry) error {

	if err := validate.Required("GetRestapiV10AccountAccountIDExtensionExtensionIDAddressBookSync default"+"."+"nextPageId", "body", o.NextPageID); err != nil {
		return err
	}

	return nil
}

func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDAddressBookSyncDefaultBody) validateNextPageURI(formats strfmt.Registry) error {

	if err := validate.Required("GetRestapiV10AccountAccountIDExtensionExtensionIDAddressBookSync default"+"."+"nextPageUri", "body", o.NextPageURI); err != nil {
		return err
	}

	return nil
}

func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDAddressBookSyncDefaultBody) validateRecords(formats strfmt.Registry) error {

	if err := validate.Required("GetRestapiV10AccountAccountIDExtensionExtensionIDAddressBookSync default"+"."+"records", "body", o.Records); err != nil {
		return err
	}

	for i := 0; i < len(o.Records); i++ {

		if swag.IsZero(o.Records[i]) { // not required
			continue
		}

		if o.Records[i] != nil {

			if err := o.Records[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("GetRestapiV10AccountAccountIDExtensionExtensionIDAddressBookSync default" + "." + "records" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDAddressBookSyncDefaultBody) validateSyncInfo(formats strfmt.Registry) error {

	if err := validate.Required("GetRestapiV10AccountAccountIDExtensionExtensionIDAddressBookSync default"+"."+"syncInfo", "body", o.SyncInfo); err != nil {
		return err
	}

	if o.SyncInfo != nil {

		if err := o.SyncInfo.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("GetRestapiV10AccountAccountIDExtensionExtensionIDAddressBookSync default" + "." + "syncInfo")
			}
			return err
		}
	}

	return nil
}
