package address_book

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/grokify/go-ringcentral/models"
)

// PostRestapiV10AccountAccountIDExtensionExtensionIDAddressBookContactReader is a Reader for the PostRestapiV10AccountAccountIDExtensionExtensionIDAddressBookContact structure.
type PostRestapiV10AccountAccountIDExtensionExtensionIDAddressBookContactReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostRestapiV10AccountAccountIDExtensionExtensionIDAddressBookContactReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {

	result := NewPostRestapiV10AccountAccountIDExtensionExtensionIDAddressBookContactDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result

}

// NewPostRestapiV10AccountAccountIDExtensionExtensionIDAddressBookContactDefault creates a PostRestapiV10AccountAccountIDExtensionExtensionIDAddressBookContactDefault with default headers values
func NewPostRestapiV10AccountAccountIDExtensionExtensionIDAddressBookContactDefault(code int) *PostRestapiV10AccountAccountIDExtensionExtensionIDAddressBookContactDefault {
	return &PostRestapiV10AccountAccountIDExtensionExtensionIDAddressBookContactDefault{
		_statusCode: code,
	}
}

/*PostRestapiV10AccountAccountIDExtensionExtensionIDAddressBookContactDefault handles this case with default header values.

OK
*/
type PostRestapiV10AccountAccountIDExtensionExtensionIDAddressBookContactDefault struct {
	_statusCode int

	Payload *models.PersonalContactInfo
}

// Code gets the status code for the post restapi v10 account account ID extension extension ID address book contact default response
func (o *PostRestapiV10AccountAccountIDExtensionExtensionIDAddressBookContactDefault) Code() int {
	return o._statusCode
}

func (o *PostRestapiV10AccountAccountIDExtensionExtensionIDAddressBookContactDefault) Error() string {
	return fmt.Sprintf("[POST /restapi/v1.0/account/{accountId}/extension/{extensionId}/address-book/contact][%d] PostRestapiV10AccountAccountIDExtensionExtensionIDAddressBookContact default  %+v", o._statusCode, o.Payload)
}

func (o *PostRestapiV10AccountAccountIDExtensionExtensionIDAddressBookContactDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PersonalContactInfo)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
