package phone_number_parser

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostRestapiV10NumberParserParseParams creates a new PostRestapiV10NumberParserParseParams object
// with the default values initialized.
func NewPostRestapiV10NumberParserParseParams() *PostRestapiV10NumberParserParseParams {
	var ()
	return &PostRestapiV10NumberParserParseParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostRestapiV10NumberParserParseParamsWithTimeout creates a new PostRestapiV10NumberParserParseParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostRestapiV10NumberParserParseParamsWithTimeout(timeout time.Duration) *PostRestapiV10NumberParserParseParams {
	var ()
	return &PostRestapiV10NumberParserParseParams{

		timeout: timeout,
	}
}

// NewPostRestapiV10NumberParserParseParamsWithContext creates a new PostRestapiV10NumberParserParseParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostRestapiV10NumberParserParseParamsWithContext(ctx context.Context) *PostRestapiV10NumberParserParseParams {
	var ()
	return &PostRestapiV10NumberParserParseParams{

		Context: ctx,
	}
}

// NewPostRestapiV10NumberParserParseParamsWithHTTPClient creates a new PostRestapiV10NumberParserParseParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostRestapiV10NumberParserParseParamsWithHTTPClient(client *http.Client) *PostRestapiV10NumberParserParseParams {
	var ()
	return &PostRestapiV10NumberParserParseParams{
		HTTPClient: client,
	}
}

/*PostRestapiV10NumberParserParseParams contains all the parameters to send to the API endpoint
for the post restapi v10 number parser parse operation typically these are written to a http.Request
*/
type PostRestapiV10NumberParserParseParams struct {

	/*Body*/
	Body PostRestapiV10NumberParserParseBody
	/*HomeCountry
	  Internal identifier of a home country. The default value is ISO code (ISO 3166) of the user's home country or brand country, if the user is undefined

	*/
	HomeCountry *string
	/*NationalAsPriority
	  The default value is "False". If "True", the numbers that are closer to the home country are given higher priority

	*/
	NationalAsPriority *bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post restapi v10 number parser parse params
func (o *PostRestapiV10NumberParserParseParams) WithTimeout(timeout time.Duration) *PostRestapiV10NumberParserParseParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post restapi v10 number parser parse params
func (o *PostRestapiV10NumberParserParseParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post restapi v10 number parser parse params
func (o *PostRestapiV10NumberParserParseParams) WithContext(ctx context.Context) *PostRestapiV10NumberParserParseParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post restapi v10 number parser parse params
func (o *PostRestapiV10NumberParserParseParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post restapi v10 number parser parse params
func (o *PostRestapiV10NumberParserParseParams) WithHTTPClient(client *http.Client) *PostRestapiV10NumberParserParseParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post restapi v10 number parser parse params
func (o *PostRestapiV10NumberParserParseParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post restapi v10 number parser parse params
func (o *PostRestapiV10NumberParserParseParams) WithBody(body PostRestapiV10NumberParserParseBody) *PostRestapiV10NumberParserParseParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post restapi v10 number parser parse params
func (o *PostRestapiV10NumberParserParseParams) SetBody(body PostRestapiV10NumberParserParseBody) {
	o.Body = body
}

// WithHomeCountry adds the homeCountry to the post restapi v10 number parser parse params
func (o *PostRestapiV10NumberParserParseParams) WithHomeCountry(homeCountry *string) *PostRestapiV10NumberParserParseParams {
	o.SetHomeCountry(homeCountry)
	return o
}

// SetHomeCountry adds the homeCountry to the post restapi v10 number parser parse params
func (o *PostRestapiV10NumberParserParseParams) SetHomeCountry(homeCountry *string) {
	o.HomeCountry = homeCountry
}

// WithNationalAsPriority adds the nationalAsPriority to the post restapi v10 number parser parse params
func (o *PostRestapiV10NumberParserParseParams) WithNationalAsPriority(nationalAsPriority *bool) *PostRestapiV10NumberParserParseParams {
	o.SetNationalAsPriority(nationalAsPriority)
	return o
}

// SetNationalAsPriority adds the nationalAsPriority to the post restapi v10 number parser parse params
func (o *PostRestapiV10NumberParserParseParams) SetNationalAsPriority(nationalAsPriority *bool) {
	o.NationalAsPriority = nationalAsPriority
}

// WriteToRequest writes these params to a swagger request
func (o *PostRestapiV10NumberParserParseParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if o.HomeCountry != nil {

		// query param homeCountry
		var qrHomeCountry string
		if o.HomeCountry != nil {
			qrHomeCountry = *o.HomeCountry
		}
		qHomeCountry := qrHomeCountry
		if qHomeCountry != "" {
			if err := r.SetQueryParam("homeCountry", qHomeCountry); err != nil {
				return err
			}
		}

	}

	if o.NationalAsPriority != nil {

		// query param nationalAsPriority
		var qrNationalAsPriority bool
		if o.NationalAsPriority != nil {
			qrNationalAsPriority = *o.NationalAsPriority
		}
		qNationalAsPriority := swag.FormatBool(qrNationalAsPriority)
		if qNationalAsPriority != "" {
			if err := r.SetQueryParam("nationalAsPriority", qNationalAsPriority); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
