package phone_number_pool

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/grokify/go-ringcentral/models"
)

// PostRestapiV10NumberPoolLookupReader is a Reader for the PostRestapiV10NumberPoolLookup structure.
type PostRestapiV10NumberPoolLookupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostRestapiV10NumberPoolLookupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {

	result := NewPostRestapiV10NumberPoolLookupDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result

}

// NewPostRestapiV10NumberPoolLookupDefault creates a PostRestapiV10NumberPoolLookupDefault with default headers values
func NewPostRestapiV10NumberPoolLookupDefault(code int) *PostRestapiV10NumberPoolLookupDefault {
	return &PostRestapiV10NumberPoolLookupDefault{
		_statusCode: code,
	}
}

/*PostRestapiV10NumberPoolLookupDefault handles this case with default header values.

OK
*/
type PostRestapiV10NumberPoolLookupDefault struct {
	_statusCode int

	Payload PostRestapiV10NumberPoolLookupDefaultBody
}

// Code gets the status code for the post restapi v10 number pool lookup default response
func (o *PostRestapiV10NumberPoolLookupDefault) Code() int {
	return o._statusCode
}

func (o *PostRestapiV10NumberPoolLookupDefault) Error() string {
	return fmt.Sprintf("[POST /restapi/v1.0/number-pool/lookup][%d] PostRestapiV10NumberPoolLookup default  %+v", o._statusCode, o.Payload)
}

func (o *PostRestapiV10NumberPoolLookupDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*PostRestapiV10NumberPoolLookupDefaultBody post restapi v10 number pool lookup default body
swagger:model PostRestapiV10NumberPoolLookupDefaultBody
*/
type PostRestapiV10NumberPoolLookupDefaultBody struct {

	// List of phone numbers filtered by the specified criteria
	// Required: true
	Records []*models.LookUpPhoneNumberPhoneNumberInfo `json:"records"`

	// Canonical URI of the phone numbers resource
	// Required: true
	URI *string `json:"uri"`
}

// Validate validates this post restapi v10 number pool lookup default body
func (o *PostRestapiV10NumberPoolLookupDefaultBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateRecords(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := o.validateURI(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostRestapiV10NumberPoolLookupDefaultBody) validateRecords(formats strfmt.Registry) error {

	if err := validate.Required("PostRestapiV10NumberPoolLookup default"+"."+"records", "body", o.Records); err != nil {
		return err
	}

	for i := 0; i < len(o.Records); i++ {

		if swag.IsZero(o.Records[i]) { // not required
			continue
		}

		if o.Records[i] != nil {

			if err := o.Records[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("PostRestapiV10NumberPoolLookup default" + "." + "records" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *PostRestapiV10NumberPoolLookupDefaultBody) validateURI(formats strfmt.Registry) error {

	if err := validate.Required("PostRestapiV10NumberPoolLookup default"+"."+"uri", "body", o.URI); err != nil {
		return err
	}

	return nil
}
