package push_notifications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetRestapiV10SubscriptionParams creates a new GetRestapiV10SubscriptionParams object
// with the default values initialized.
func NewGetRestapiV10SubscriptionParams() *GetRestapiV10SubscriptionParams {

	return &GetRestapiV10SubscriptionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetRestapiV10SubscriptionParamsWithTimeout creates a new GetRestapiV10SubscriptionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetRestapiV10SubscriptionParamsWithTimeout(timeout time.Duration) *GetRestapiV10SubscriptionParams {

	return &GetRestapiV10SubscriptionParams{

		timeout: timeout,
	}
}

// NewGetRestapiV10SubscriptionParamsWithContext creates a new GetRestapiV10SubscriptionParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetRestapiV10SubscriptionParamsWithContext(ctx context.Context) *GetRestapiV10SubscriptionParams {

	return &GetRestapiV10SubscriptionParams{

		Context: ctx,
	}
}

// NewGetRestapiV10SubscriptionParamsWithHTTPClient creates a new GetRestapiV10SubscriptionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetRestapiV10SubscriptionParamsWithHTTPClient(client *http.Client) *GetRestapiV10SubscriptionParams {

	return &GetRestapiV10SubscriptionParams{
		HTTPClient: client,
	}
}

/*GetRestapiV10SubscriptionParams contains all the parameters to send to the API endpoint
for the get restapi v10 subscription operation typically these are written to a http.Request
*/
type GetRestapiV10SubscriptionParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get restapi v10 subscription params
func (o *GetRestapiV10SubscriptionParams) WithTimeout(timeout time.Duration) *GetRestapiV10SubscriptionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get restapi v10 subscription params
func (o *GetRestapiV10SubscriptionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get restapi v10 subscription params
func (o *GetRestapiV10SubscriptionParams) WithContext(ctx context.Context) *GetRestapiV10SubscriptionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get restapi v10 subscription params
func (o *GetRestapiV10SubscriptionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get restapi v10 subscription params
func (o *GetRestapiV10SubscriptionParams) WithHTTPClient(client *http.Client) *GetRestapiV10SubscriptionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get restapi v10 subscription params
func (o *GetRestapiV10SubscriptionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetRestapiV10SubscriptionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
