package push_notifications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPutRestapiV10SubscriptionSubscriptionIDParams creates a new PutRestapiV10SubscriptionSubscriptionIDParams object
// with the default values initialized.
func NewPutRestapiV10SubscriptionSubscriptionIDParams() *PutRestapiV10SubscriptionSubscriptionIDParams {
	var ()
	return &PutRestapiV10SubscriptionSubscriptionIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutRestapiV10SubscriptionSubscriptionIDParamsWithTimeout creates a new PutRestapiV10SubscriptionSubscriptionIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutRestapiV10SubscriptionSubscriptionIDParamsWithTimeout(timeout time.Duration) *PutRestapiV10SubscriptionSubscriptionIDParams {
	var ()
	return &PutRestapiV10SubscriptionSubscriptionIDParams{

		timeout: timeout,
	}
}

// NewPutRestapiV10SubscriptionSubscriptionIDParamsWithContext creates a new PutRestapiV10SubscriptionSubscriptionIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutRestapiV10SubscriptionSubscriptionIDParamsWithContext(ctx context.Context) *PutRestapiV10SubscriptionSubscriptionIDParams {
	var ()
	return &PutRestapiV10SubscriptionSubscriptionIDParams{

		Context: ctx,
	}
}

// NewPutRestapiV10SubscriptionSubscriptionIDParamsWithHTTPClient creates a new PutRestapiV10SubscriptionSubscriptionIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutRestapiV10SubscriptionSubscriptionIDParamsWithHTTPClient(client *http.Client) *PutRestapiV10SubscriptionSubscriptionIDParams {
	var ()
	return &PutRestapiV10SubscriptionSubscriptionIDParams{
		HTTPClient: client,
	}
}

/*PutRestapiV10SubscriptionSubscriptionIDParams contains all the parameters to send to the API endpoint
for the put restapi v10 subscription subscription ID operation typically these are written to a http.Request
*/
type PutRestapiV10SubscriptionSubscriptionIDParams struct {

	/*Body*/
	Body PutRestapiV10SubscriptionSubscriptionIDBody
	/*SubscriptionID
	  Internal identifier of a subscription

	*/
	SubscriptionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put restapi v10 subscription subscription ID params
func (o *PutRestapiV10SubscriptionSubscriptionIDParams) WithTimeout(timeout time.Duration) *PutRestapiV10SubscriptionSubscriptionIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put restapi v10 subscription subscription ID params
func (o *PutRestapiV10SubscriptionSubscriptionIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put restapi v10 subscription subscription ID params
func (o *PutRestapiV10SubscriptionSubscriptionIDParams) WithContext(ctx context.Context) *PutRestapiV10SubscriptionSubscriptionIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put restapi v10 subscription subscription ID params
func (o *PutRestapiV10SubscriptionSubscriptionIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put restapi v10 subscription subscription ID params
func (o *PutRestapiV10SubscriptionSubscriptionIDParams) WithHTTPClient(client *http.Client) *PutRestapiV10SubscriptionSubscriptionIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put restapi v10 subscription subscription ID params
func (o *PutRestapiV10SubscriptionSubscriptionIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the put restapi v10 subscription subscription ID params
func (o *PutRestapiV10SubscriptionSubscriptionIDParams) WithBody(body PutRestapiV10SubscriptionSubscriptionIDBody) *PutRestapiV10SubscriptionSubscriptionIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put restapi v10 subscription subscription ID params
func (o *PutRestapiV10SubscriptionSubscriptionIDParams) SetBody(body PutRestapiV10SubscriptionSubscriptionIDBody) {
	o.Body = body
}

// WithSubscriptionID adds the subscriptionID to the put restapi v10 subscription subscription ID params
func (o *PutRestapiV10SubscriptionSubscriptionIDParams) WithSubscriptionID(subscriptionID string) *PutRestapiV10SubscriptionSubscriptionIDParams {
	o.SetSubscriptionID(subscriptionID)
	return o
}

// SetSubscriptionID adds the subscriptionId to the put restapi v10 subscription subscription ID params
func (o *PutRestapiV10SubscriptionSubscriptionIDParams) SetSubscriptionID(subscriptionID string) {
	o.SubscriptionID = subscriptionID
}

// WriteToRequest writes these params to a swagger request
func (o *PutRestapiV10SubscriptionSubscriptionIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param subscriptionId
	if err := r.SetPathParam("subscriptionId", o.SubscriptionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
