package extension

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetRestapiV10AccountAccountIDExtensionExtensionIDPhoneNumberParams creates a new GetRestapiV10AccountAccountIDExtensionExtensionIDPhoneNumberParams object
// with the default values initialized.
func NewGetRestapiV10AccountAccountIDExtensionExtensionIDPhoneNumberParams() *GetRestapiV10AccountAccountIDExtensionExtensionIDPhoneNumberParams {
	var (
		accountIDDefault   = string("~")
		extensionIDDefault = string("~")
	)
	return &GetRestapiV10AccountAccountIDExtensionExtensionIDPhoneNumberParams{
		AccountID:   accountIDDefault,
		ExtensionID: extensionIDDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetRestapiV10AccountAccountIDExtensionExtensionIDPhoneNumberParamsWithTimeout creates a new GetRestapiV10AccountAccountIDExtensionExtensionIDPhoneNumberParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetRestapiV10AccountAccountIDExtensionExtensionIDPhoneNumberParamsWithTimeout(timeout time.Duration) *GetRestapiV10AccountAccountIDExtensionExtensionIDPhoneNumberParams {
	var (
		accountIDDefault   = string("~")
		extensionIDDefault = string("~")
	)
	return &GetRestapiV10AccountAccountIDExtensionExtensionIDPhoneNumberParams{
		AccountID:   accountIDDefault,
		ExtensionID: extensionIDDefault,

		timeout: timeout,
	}
}

// NewGetRestapiV10AccountAccountIDExtensionExtensionIDPhoneNumberParamsWithContext creates a new GetRestapiV10AccountAccountIDExtensionExtensionIDPhoneNumberParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetRestapiV10AccountAccountIDExtensionExtensionIDPhoneNumberParamsWithContext(ctx context.Context) *GetRestapiV10AccountAccountIDExtensionExtensionIDPhoneNumberParams {
	var (
		accountIdDefault   = string("~")
		extensionIdDefault = string("~")
	)
	return &GetRestapiV10AccountAccountIDExtensionExtensionIDPhoneNumberParams{
		AccountID:   accountIdDefault,
		ExtensionID: extensionIdDefault,

		Context: ctx,
	}
}

// NewGetRestapiV10AccountAccountIDExtensionExtensionIDPhoneNumberParamsWithHTTPClient creates a new GetRestapiV10AccountAccountIDExtensionExtensionIDPhoneNumberParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetRestapiV10AccountAccountIDExtensionExtensionIDPhoneNumberParamsWithHTTPClient(client *http.Client) *GetRestapiV10AccountAccountIDExtensionExtensionIDPhoneNumberParams {
	var (
		accountIdDefault   = string("~")
		extensionIdDefault = string("~")
	)
	return &GetRestapiV10AccountAccountIDExtensionExtensionIDPhoneNumberParams{
		AccountID:   accountIdDefault,
		ExtensionID: extensionIdDefault,
		HTTPClient:  client,
	}
}

/*GetRestapiV10AccountAccountIDExtensionExtensionIDPhoneNumberParams contains all the parameters to send to the API endpoint
for the get restapi v10 account account ID extension extension ID phone number operation typically these are written to a http.Request
*/
type GetRestapiV10AccountAccountIDExtensionExtensionIDPhoneNumberParams struct {

	/*AccountID
	  Internal identifier of a RingCentral account or tilde (~) to indicate the account logged-in within the current session

	*/
	AccountID string
	/*ExtensionID
	  Internal identifier of an extension or tilde (~) to indicate the extension assigned to the account logged-in within the current session

	*/
	ExtensionID string
	/*Page
	  Indicates the page number to retrieve. Only positive number values are allowed. Default value is '1'

	*/
	Page *int64
	/*PerPage
	  Indicates the page size (number of items). If not specified, the value is '100' by default

	*/
	PerPage *int64
	/*UsageType
	  Usage type of the phone number

	*/
	UsageType *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get restapi v10 account account ID extension extension ID phone number params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDPhoneNumberParams) WithTimeout(timeout time.Duration) *GetRestapiV10AccountAccountIDExtensionExtensionIDPhoneNumberParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get restapi v10 account account ID extension extension ID phone number params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDPhoneNumberParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get restapi v10 account account ID extension extension ID phone number params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDPhoneNumberParams) WithContext(ctx context.Context) *GetRestapiV10AccountAccountIDExtensionExtensionIDPhoneNumberParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get restapi v10 account account ID extension extension ID phone number params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDPhoneNumberParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get restapi v10 account account ID extension extension ID phone number params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDPhoneNumberParams) WithHTTPClient(client *http.Client) *GetRestapiV10AccountAccountIDExtensionExtensionIDPhoneNumberParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get restapi v10 account account ID extension extension ID phone number params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDPhoneNumberParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccountID adds the accountID to the get restapi v10 account account ID extension extension ID phone number params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDPhoneNumberParams) WithAccountID(accountID string) *GetRestapiV10AccountAccountIDExtensionExtensionIDPhoneNumberParams {
	o.SetAccountID(accountID)
	return o
}

// SetAccountID adds the accountId to the get restapi v10 account account ID extension extension ID phone number params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDPhoneNumberParams) SetAccountID(accountID string) {
	o.AccountID = accountID
}

// WithExtensionID adds the extensionID to the get restapi v10 account account ID extension extension ID phone number params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDPhoneNumberParams) WithExtensionID(extensionID string) *GetRestapiV10AccountAccountIDExtensionExtensionIDPhoneNumberParams {
	o.SetExtensionID(extensionID)
	return o
}

// SetExtensionID adds the extensionId to the get restapi v10 account account ID extension extension ID phone number params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDPhoneNumberParams) SetExtensionID(extensionID string) {
	o.ExtensionID = extensionID
}

// WithPage adds the page to the get restapi v10 account account ID extension extension ID phone number params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDPhoneNumberParams) WithPage(page *int64) *GetRestapiV10AccountAccountIDExtensionExtensionIDPhoneNumberParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the get restapi v10 account account ID extension extension ID phone number params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDPhoneNumberParams) SetPage(page *int64) {
	o.Page = page
}

// WithPerPage adds the perPage to the get restapi v10 account account ID extension extension ID phone number params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDPhoneNumberParams) WithPerPage(perPage *int64) *GetRestapiV10AccountAccountIDExtensionExtensionIDPhoneNumberParams {
	o.SetPerPage(perPage)
	return o
}

// SetPerPage adds the perPage to the get restapi v10 account account ID extension extension ID phone number params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDPhoneNumberParams) SetPerPage(perPage *int64) {
	o.PerPage = perPage
}

// WithUsageType adds the usageType to the get restapi v10 account account ID extension extension ID phone number params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDPhoneNumberParams) WithUsageType(usageType *string) *GetRestapiV10AccountAccountIDExtensionExtensionIDPhoneNumberParams {
	o.SetUsageType(usageType)
	return o
}

// SetUsageType adds the usageType to the get restapi v10 account account ID extension extension ID phone number params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDPhoneNumberParams) SetUsageType(usageType *string) {
	o.UsageType = usageType
}

// WriteToRequest writes these params to a swagger request
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDPhoneNumberParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param accountId
	if err := r.SetPathParam("accountId", o.AccountID); err != nil {
		return err
	}

	// path param extensionId
	if err := r.SetPathParam("extensionId", o.ExtensionID); err != nil {
		return err
	}

	if o.Page != nil {

		// query param page
		var qrPage int64
		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt64(qrPage)
		if qPage != "" {
			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}

	}

	if o.PerPage != nil {

		// query param perPage
		var qrPerPage int64
		if o.PerPage != nil {
			qrPerPage = *o.PerPage
		}
		qPerPage := swag.FormatInt64(qrPerPage)
		if qPerPage != "" {
			if err := r.SetQueryParam("perPage", qPerPage); err != nil {
				return err
			}
		}

	}

	if o.UsageType != nil {

		// query param usageType
		var qrUsageType string
		if o.UsageType != nil {
			qrUsageType = *o.UsageType
		}
		qUsageType := qrUsageType
		if qUsageType != "" {
			if err := r.SetQueryParam("usageType", qUsageType); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
