package extension

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetRestapiV10AccountAccountIDDepartmentDepartmentIDMembersParams creates a new GetRestapiV10AccountAccountIDDepartmentDepartmentIDMembersParams object
// with the default values initialized.
func NewGetRestapiV10AccountAccountIDDepartmentDepartmentIDMembersParams() *GetRestapiV10AccountAccountIDDepartmentDepartmentIDMembersParams {
	var (
		accountIDDefault = string("~")
	)
	return &GetRestapiV10AccountAccountIDDepartmentDepartmentIDMembersParams{
		AccountID: accountIDDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetRestapiV10AccountAccountIDDepartmentDepartmentIDMembersParamsWithTimeout creates a new GetRestapiV10AccountAccountIDDepartmentDepartmentIDMembersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetRestapiV10AccountAccountIDDepartmentDepartmentIDMembersParamsWithTimeout(timeout time.Duration) *GetRestapiV10AccountAccountIDDepartmentDepartmentIDMembersParams {
	var (
		accountIDDefault = string("~")
	)
	return &GetRestapiV10AccountAccountIDDepartmentDepartmentIDMembersParams{
		AccountID: accountIDDefault,

		timeout: timeout,
	}
}

// NewGetRestapiV10AccountAccountIDDepartmentDepartmentIDMembersParamsWithContext creates a new GetRestapiV10AccountAccountIDDepartmentDepartmentIDMembersParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetRestapiV10AccountAccountIDDepartmentDepartmentIDMembersParamsWithContext(ctx context.Context) *GetRestapiV10AccountAccountIDDepartmentDepartmentIDMembersParams {
	var (
		accountIdDefault = string("~")
	)
	return &GetRestapiV10AccountAccountIDDepartmentDepartmentIDMembersParams{
		AccountID: accountIdDefault,

		Context: ctx,
	}
}

// NewGetRestapiV10AccountAccountIDDepartmentDepartmentIDMembersParamsWithHTTPClient creates a new GetRestapiV10AccountAccountIDDepartmentDepartmentIDMembersParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetRestapiV10AccountAccountIDDepartmentDepartmentIDMembersParamsWithHTTPClient(client *http.Client) *GetRestapiV10AccountAccountIDDepartmentDepartmentIDMembersParams {
	var (
		accountIdDefault = string("~")
	)
	return &GetRestapiV10AccountAccountIDDepartmentDepartmentIDMembersParams{
		AccountID:  accountIdDefault,
		HTTPClient: client,
	}
}

/*GetRestapiV10AccountAccountIDDepartmentDepartmentIDMembersParams contains all the parameters to send to the API endpoint
for the get restapi v10 account account ID department department ID members operation typically these are written to a http.Request
*/
type GetRestapiV10AccountAccountIDDepartmentDepartmentIDMembersParams struct {

	/*AccountID
	  Internal identifier of a RingCentral account or tilde (~) to indicate the account logged-in within the current session

	*/
	AccountID string
	/*DepartmentID
	  Internal identifier of a Department extension (same as extensionId but only the ID of a department extension is valid)

	*/
	DepartmentID string
	/*Page
	  Indicates the page number to retrieve. Only positive number values are allowed. Default value is '1'

	*/
	Page *int64
	/*PerPage
	  Indicates the page size (number of items). If not specified, the value is '100' by default

	*/
	PerPage *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get restapi v10 account account ID department department ID members params
func (o *GetRestapiV10AccountAccountIDDepartmentDepartmentIDMembersParams) WithTimeout(timeout time.Duration) *GetRestapiV10AccountAccountIDDepartmentDepartmentIDMembersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get restapi v10 account account ID department department ID members params
func (o *GetRestapiV10AccountAccountIDDepartmentDepartmentIDMembersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get restapi v10 account account ID department department ID members params
func (o *GetRestapiV10AccountAccountIDDepartmentDepartmentIDMembersParams) WithContext(ctx context.Context) *GetRestapiV10AccountAccountIDDepartmentDepartmentIDMembersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get restapi v10 account account ID department department ID members params
func (o *GetRestapiV10AccountAccountIDDepartmentDepartmentIDMembersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get restapi v10 account account ID department department ID members params
func (o *GetRestapiV10AccountAccountIDDepartmentDepartmentIDMembersParams) WithHTTPClient(client *http.Client) *GetRestapiV10AccountAccountIDDepartmentDepartmentIDMembersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get restapi v10 account account ID department department ID members params
func (o *GetRestapiV10AccountAccountIDDepartmentDepartmentIDMembersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccountID adds the accountID to the get restapi v10 account account ID department department ID members params
func (o *GetRestapiV10AccountAccountIDDepartmentDepartmentIDMembersParams) WithAccountID(accountID string) *GetRestapiV10AccountAccountIDDepartmentDepartmentIDMembersParams {
	o.SetAccountID(accountID)
	return o
}

// SetAccountID adds the accountId to the get restapi v10 account account ID department department ID members params
func (o *GetRestapiV10AccountAccountIDDepartmentDepartmentIDMembersParams) SetAccountID(accountID string) {
	o.AccountID = accountID
}

// WithDepartmentID adds the departmentID to the get restapi v10 account account ID department department ID members params
func (o *GetRestapiV10AccountAccountIDDepartmentDepartmentIDMembersParams) WithDepartmentID(departmentID string) *GetRestapiV10AccountAccountIDDepartmentDepartmentIDMembersParams {
	o.SetDepartmentID(departmentID)
	return o
}

// SetDepartmentID adds the departmentId to the get restapi v10 account account ID department department ID members params
func (o *GetRestapiV10AccountAccountIDDepartmentDepartmentIDMembersParams) SetDepartmentID(departmentID string) {
	o.DepartmentID = departmentID
}

// WithPage adds the page to the get restapi v10 account account ID department department ID members params
func (o *GetRestapiV10AccountAccountIDDepartmentDepartmentIDMembersParams) WithPage(page *int64) *GetRestapiV10AccountAccountIDDepartmentDepartmentIDMembersParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the get restapi v10 account account ID department department ID members params
func (o *GetRestapiV10AccountAccountIDDepartmentDepartmentIDMembersParams) SetPage(page *int64) {
	o.Page = page
}

// WithPerPage adds the perPage to the get restapi v10 account account ID department department ID members params
func (o *GetRestapiV10AccountAccountIDDepartmentDepartmentIDMembersParams) WithPerPage(perPage *int64) *GetRestapiV10AccountAccountIDDepartmentDepartmentIDMembersParams {
	o.SetPerPage(perPage)
	return o
}

// SetPerPage adds the perPage to the get restapi v10 account account ID department department ID members params
func (o *GetRestapiV10AccountAccountIDDepartmentDepartmentIDMembersParams) SetPerPage(perPage *int64) {
	o.PerPage = perPage
}

// WriteToRequest writes these params to a swagger request
func (o *GetRestapiV10AccountAccountIDDepartmentDepartmentIDMembersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param accountId
	if err := r.SetPathParam("accountId", o.AccountID); err != nil {
		return err
	}

	// path param departmentId
	if err := r.SetPathParam("departmentId", o.DepartmentID); err != nil {
		return err
	}

	if o.Page != nil {

		// query param page
		var qrPage int64
		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt64(qrPage)
		if qPage != "" {
			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}

	}

	if o.PerPage != nil {

		// query param perPage
		var qrPerPage int64
		if o.PerPage != nil {
			qrPerPage = *o.PerPage
		}
		qPerPage := swag.FormatInt64(qrPerPage)
		if qPerPage != "" {
			if err := r.SetQueryParam("perPage", qPerPage); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
