package extension

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/grokify/go-ringcentral/models"
)

// GetRestapiV10AccountAccountIDExtensionExtensionIDProfileImageScaleSizeReader is a Reader for the GetRestapiV10AccountAccountIDExtensionExtensionIDProfileImageScaleSize structure.
type GetRestapiV10AccountAccountIDExtensionExtensionIDProfileImageScaleSizeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDProfileImageScaleSizeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {

	result := NewGetRestapiV10AccountAccountIDExtensionExtensionIDProfileImageScaleSizeDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result

}

// NewGetRestapiV10AccountAccountIDExtensionExtensionIDProfileImageScaleSizeDefault creates a GetRestapiV10AccountAccountIDExtensionExtensionIDProfileImageScaleSizeDefault with default headers values
func NewGetRestapiV10AccountAccountIDExtensionExtensionIDProfileImageScaleSizeDefault(code int) *GetRestapiV10AccountAccountIDExtensionExtensionIDProfileImageScaleSizeDefault {
	return &GetRestapiV10AccountAccountIDExtensionExtensionIDProfileImageScaleSizeDefault{
		_statusCode: code,
	}
}

/*GetRestapiV10AccountAccountIDExtensionExtensionIDProfileImageScaleSizeDefault handles this case with default header values.

OK
*/
type GetRestapiV10AccountAccountIDExtensionExtensionIDProfileImageScaleSizeDefault struct {
	_statusCode int

	Payload *models.Binary
}

// Code gets the status code for the get restapi v10 account account ID extension extension ID profile image scale size default response
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDProfileImageScaleSizeDefault) Code() int {
	return o._statusCode
}

func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDProfileImageScaleSizeDefault) Error() string {
	return fmt.Sprintf("[GET /restapi/v1.0/account/{accountId}/extension/{extensionId}/profile-image/{scaleSize}][%d] GetRestapiV10AccountAccountIDExtensionExtensionIDProfileImageScaleSize default  %+v", o._statusCode, o.Payload)
}

func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDProfileImageScaleSizeDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Binary)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
