package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetRestapiV10AccountAccountIDPhoneNumberParams creates a new GetRestapiV10AccountAccountIDPhoneNumberParams object
// with the default values initialized.
func NewGetRestapiV10AccountAccountIDPhoneNumberParams() *GetRestapiV10AccountAccountIDPhoneNumberParams {
	var (
		accountIDDefault = string("~")
	)
	return &GetRestapiV10AccountAccountIDPhoneNumberParams{
		AccountID: accountIDDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetRestapiV10AccountAccountIDPhoneNumberParamsWithTimeout creates a new GetRestapiV10AccountAccountIDPhoneNumberParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetRestapiV10AccountAccountIDPhoneNumberParamsWithTimeout(timeout time.Duration) *GetRestapiV10AccountAccountIDPhoneNumberParams {
	var (
		accountIDDefault = string("~")
	)
	return &GetRestapiV10AccountAccountIDPhoneNumberParams{
		AccountID: accountIDDefault,

		timeout: timeout,
	}
}

// NewGetRestapiV10AccountAccountIDPhoneNumberParamsWithContext creates a new GetRestapiV10AccountAccountIDPhoneNumberParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetRestapiV10AccountAccountIDPhoneNumberParamsWithContext(ctx context.Context) *GetRestapiV10AccountAccountIDPhoneNumberParams {
	var (
		accountIdDefault = string("~")
	)
	return &GetRestapiV10AccountAccountIDPhoneNumberParams{
		AccountID: accountIdDefault,

		Context: ctx,
	}
}

// NewGetRestapiV10AccountAccountIDPhoneNumberParamsWithHTTPClient creates a new GetRestapiV10AccountAccountIDPhoneNumberParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetRestapiV10AccountAccountIDPhoneNumberParamsWithHTTPClient(client *http.Client) *GetRestapiV10AccountAccountIDPhoneNumberParams {
	var (
		accountIdDefault = string("~")
	)
	return &GetRestapiV10AccountAccountIDPhoneNumberParams{
		AccountID:  accountIdDefault,
		HTTPClient: client,
	}
}

/*GetRestapiV10AccountAccountIDPhoneNumberParams contains all the parameters to send to the API endpoint
for the get restapi v10 account account ID phone number operation typically these are written to a http.Request
*/
type GetRestapiV10AccountAccountIDPhoneNumberParams struct {

	/*AccountID
	  Internal identifier of a RingCentral account or tilde (~) to indicate the account logged-in within the current session

	*/
	AccountID string
	/*Page
	  Indicates the page number to retrieve. Only positive number values are allowed. Default value is '1'

	*/
	Page *int64
	/*PerPage
	  Indicates the page size (number of items). If not specified, the value is '100' by default

	*/
	PerPage *int64
	/*UsageType
	  Usage type of the phone number

	*/
	UsageType *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get restapi v10 account account ID phone number params
func (o *GetRestapiV10AccountAccountIDPhoneNumberParams) WithTimeout(timeout time.Duration) *GetRestapiV10AccountAccountIDPhoneNumberParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get restapi v10 account account ID phone number params
func (o *GetRestapiV10AccountAccountIDPhoneNumberParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get restapi v10 account account ID phone number params
func (o *GetRestapiV10AccountAccountIDPhoneNumberParams) WithContext(ctx context.Context) *GetRestapiV10AccountAccountIDPhoneNumberParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get restapi v10 account account ID phone number params
func (o *GetRestapiV10AccountAccountIDPhoneNumberParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get restapi v10 account account ID phone number params
func (o *GetRestapiV10AccountAccountIDPhoneNumberParams) WithHTTPClient(client *http.Client) *GetRestapiV10AccountAccountIDPhoneNumberParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get restapi v10 account account ID phone number params
func (o *GetRestapiV10AccountAccountIDPhoneNumberParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccountID adds the accountID to the get restapi v10 account account ID phone number params
func (o *GetRestapiV10AccountAccountIDPhoneNumberParams) WithAccountID(accountID string) *GetRestapiV10AccountAccountIDPhoneNumberParams {
	o.SetAccountID(accountID)
	return o
}

// SetAccountID adds the accountId to the get restapi v10 account account ID phone number params
func (o *GetRestapiV10AccountAccountIDPhoneNumberParams) SetAccountID(accountID string) {
	o.AccountID = accountID
}

// WithPage adds the page to the get restapi v10 account account ID phone number params
func (o *GetRestapiV10AccountAccountIDPhoneNumberParams) WithPage(page *int64) *GetRestapiV10AccountAccountIDPhoneNumberParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the get restapi v10 account account ID phone number params
func (o *GetRestapiV10AccountAccountIDPhoneNumberParams) SetPage(page *int64) {
	o.Page = page
}

// WithPerPage adds the perPage to the get restapi v10 account account ID phone number params
func (o *GetRestapiV10AccountAccountIDPhoneNumberParams) WithPerPage(perPage *int64) *GetRestapiV10AccountAccountIDPhoneNumberParams {
	o.SetPerPage(perPage)
	return o
}

// SetPerPage adds the perPage to the get restapi v10 account account ID phone number params
func (o *GetRestapiV10AccountAccountIDPhoneNumberParams) SetPerPage(perPage *int64) {
	o.PerPage = perPage
}

// WithUsageType adds the usageType to the get restapi v10 account account ID phone number params
func (o *GetRestapiV10AccountAccountIDPhoneNumberParams) WithUsageType(usageType *string) *GetRestapiV10AccountAccountIDPhoneNumberParams {
	o.SetUsageType(usageType)
	return o
}

// SetUsageType adds the usageType to the get restapi v10 account account ID phone number params
func (o *GetRestapiV10AccountAccountIDPhoneNumberParams) SetUsageType(usageType *string) {
	o.UsageType = usageType
}

// WriteToRequest writes these params to a swagger request
func (o *GetRestapiV10AccountAccountIDPhoneNumberParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param accountId
	if err := r.SetPathParam("accountId", o.AccountID); err != nil {
		return err
	}

	if o.Page != nil {

		// query param page
		var qrPage int64
		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt64(qrPage)
		if qPage != "" {
			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}

	}

	if o.PerPage != nil {

		// query param perPage
		var qrPerPage int64
		if o.PerPage != nil {
			qrPerPage = *o.PerPage
		}
		qPerPage := swag.FormatInt64(qrPerPage)
		if qPerPage != "" {
			if err := r.SetQueryParam("perPage", qPerPage); err != nil {
				return err
			}
		}

	}

	if o.UsageType != nil {

		// query param usageType
		var qrUsageType string
		if o.UsageType != nil {
			qrUsageType = *o.UsageType
		}
		qUsageType := qrUsageType
		if qUsageType != "" {
			if err := r.SetQueryParam("usageType", qUsageType); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
