package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/grokify/go-ringcentral/models"
)

// PutRestapiV10AccountAccountIDBusinessAddressReader is a Reader for the PutRestapiV10AccountAccountIDBusinessAddress structure.
type PutRestapiV10AccountAccountIDBusinessAddressReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutRestapiV10AccountAccountIDBusinessAddressReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {

	result := NewPutRestapiV10AccountAccountIDBusinessAddressDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result

}

// NewPutRestapiV10AccountAccountIDBusinessAddressDefault creates a PutRestapiV10AccountAccountIDBusinessAddressDefault with default headers values
func NewPutRestapiV10AccountAccountIDBusinessAddressDefault(code int) *PutRestapiV10AccountAccountIDBusinessAddressDefault {
	return &PutRestapiV10AccountAccountIDBusinessAddressDefault{
		_statusCode: code,
	}
}

/*PutRestapiV10AccountAccountIDBusinessAddressDefault handles this case with default header values.

OK
*/
type PutRestapiV10AccountAccountIDBusinessAddressDefault struct {
	_statusCode int

	Payload PutRestapiV10AccountAccountIDBusinessAddressDefaultBody
}

// Code gets the status code for the put restapi v10 account account ID business address default response
func (o *PutRestapiV10AccountAccountIDBusinessAddressDefault) Code() int {
	return o._statusCode
}

func (o *PutRestapiV10AccountAccountIDBusinessAddressDefault) Error() string {
	return fmt.Sprintf("[PUT /restapi/v1.0/account/{accountId}/business-address][%d] PutRestapiV10AccountAccountIDBusinessAddress default  %+v", o._statusCode, o.Payload)
}

func (o *PutRestapiV10AccountAccountIDBusinessAddressDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*PutRestapiV10AccountAccountIDBusinessAddressBody put restapi v10 account account ID business address body
swagger:model PutRestapiV10AccountAccountIDBusinessAddressBody
*/
type PutRestapiV10AccountAccountIDBusinessAddressBody struct {

	// Company business address
	BusinessAddress *models.BusinessAddressInfo `json:"businessAddress,omitempty"`

	// Company business name
	Company string `json:"company,omitempty"`

	// Company business email address
	Email string `json:"email,omitempty"`
}

/*PutRestapiV10AccountAccountIDBusinessAddressDefaultBody put restapi v10 account account ID business address default body
swagger:model PutRestapiV10AccountAccountIDBusinessAddressDefaultBody
*/
type PutRestapiV10AccountAccountIDBusinessAddressDefaultBody struct {

	// Company business address
	// Required: true
	BusinessAddress *models.BusinessAddressInfo `json:"businessAddress"`

	// Company business name
	// Required: true
	Company *string `json:"company"`

	// Company business email address
	// Required: true
	Email *string `json:"email"`

	// Canonical URI of the business address resource
	// Required: true
	URI *string `json:"uri"`
}

// Validate validates this put restapi v10 account account ID business address default body
func (o *PutRestapiV10AccountAccountIDBusinessAddressDefaultBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateBusinessAddress(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := o.validateCompany(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := o.validateEmail(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := o.validateURI(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PutRestapiV10AccountAccountIDBusinessAddressDefaultBody) validateBusinessAddress(formats strfmt.Registry) error {

	if err := validate.Required("PutRestapiV10AccountAccountIDBusinessAddress default"+"."+"businessAddress", "body", o.BusinessAddress); err != nil {
		return err
	}

	if o.BusinessAddress != nil {

		if err := o.BusinessAddress.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("PutRestapiV10AccountAccountIDBusinessAddress default" + "." + "businessAddress")
			}
			return err
		}
	}

	return nil
}

func (o *PutRestapiV10AccountAccountIDBusinessAddressDefaultBody) validateCompany(formats strfmt.Registry) error {

	if err := validate.Required("PutRestapiV10AccountAccountIDBusinessAddress default"+"."+"company", "body", o.Company); err != nil {
		return err
	}

	return nil
}

func (o *PutRestapiV10AccountAccountIDBusinessAddressDefaultBody) validateEmail(formats strfmt.Registry) error {

	if err := validate.Required("PutRestapiV10AccountAccountIDBusinessAddress default"+"."+"email", "body", o.Email); err != nil {
		return err
	}

	return nil
}

func (o *PutRestapiV10AccountAccountIDBusinessAddressDefaultBody) validateURI(formats strfmt.Registry) error {

	if err := validate.Required("PutRestapiV10AccountAccountIDBusinessAddress default"+"."+"uri", "body", o.URI); err != nil {
		return err
	}

	return nil
}
