package answering_rules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleAnsweringRuleIDReader is a Reader for the DeleteRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleAnsweringRuleID structure.
type DeleteRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleAnsweringRuleIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleAnsweringRuleIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {

	result := NewDeleteRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleAnsweringRuleIDDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result

}

// NewDeleteRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleAnsweringRuleIDDefault creates a DeleteRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleAnsweringRuleIDDefault with default headers values
func NewDeleteRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleAnsweringRuleIDDefault(code int) *DeleteRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleAnsweringRuleIDDefault {
	return &DeleteRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleAnsweringRuleIDDefault{
		_statusCode: code,
	}
}

/*DeleteRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleAnsweringRuleIDDefault handles this case with default header values.

OK
*/
type DeleteRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleAnsweringRuleIDDefault struct {
	_statusCode int
}

// Code gets the status code for the delete restapi v10 account account ID extension extension ID answering rule answering rule ID default response
func (o *DeleteRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleAnsweringRuleIDDefault) Code() int {
	return o._statusCode
}

func (o *DeleteRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleAnsweringRuleIDDefault) Error() string {
	return fmt.Sprintf("[DELETE /restapi/v1.0/account/{accountId}/extension/{extensionId}/answering-rule/{answeringRuleId}][%d] DeleteRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleAnsweringRuleID default ", o._statusCode)
}

func (o *DeleteRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleAnsweringRuleIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
