package answering_rules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleParams creates a new GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleParams object
// with the default values initialized.
func NewGetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleParams() *GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleParams {
	var (
		accountIDDefault   = string("~")
		extensionIDDefault = string("~")
	)
	return &GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleParams{
		AccountID:   accountIDDefault,
		ExtensionID: extensionIDDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleParamsWithTimeout creates a new GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleParamsWithTimeout(timeout time.Duration) *GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleParams {
	var (
		accountIDDefault   = string("~")
		extensionIDDefault = string("~")
	)
	return &GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleParams{
		AccountID:   accountIDDefault,
		ExtensionID: extensionIDDefault,

		timeout: timeout,
	}
}

// NewGetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleParamsWithContext creates a new GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleParamsWithContext(ctx context.Context) *GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleParams {
	var (
		accountIdDefault   = string("~")
		extensionIdDefault = string("~")
	)
	return &GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleParams{
		AccountID:   accountIdDefault,
		ExtensionID: extensionIdDefault,

		Context: ctx,
	}
}

// NewGetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleParamsWithHTTPClient creates a new GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleParamsWithHTTPClient(client *http.Client) *GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleParams {
	var (
		accountIdDefault   = string("~")
		extensionIdDefault = string("~")
	)
	return &GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleParams{
		AccountID:   accountIdDefault,
		ExtensionID: extensionIdDefault,
		HTTPClient:  client,
	}
}

/*GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleParams contains all the parameters to send to the API endpoint
for the get restapi v10 account account ID extension extension ID answering rule operation typically these are written to a http.Request
*/
type GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleParams struct {

	/*AccountID
	  Internal identifier of a RingCentral account or tilde (~) to indicate the account logged-in within the current session

	*/
	AccountID string
	/*ExtensionID
	  Internal identifier of an extension or tilde (~) to indicate the extension assigned to the account logged-in within the current session

	*/
	ExtensionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get restapi v10 account account ID extension extension ID answering rule params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleParams) WithTimeout(timeout time.Duration) *GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get restapi v10 account account ID extension extension ID answering rule params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get restapi v10 account account ID extension extension ID answering rule params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleParams) WithContext(ctx context.Context) *GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get restapi v10 account account ID extension extension ID answering rule params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get restapi v10 account account ID extension extension ID answering rule params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleParams) WithHTTPClient(client *http.Client) *GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get restapi v10 account account ID extension extension ID answering rule params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccountID adds the accountID to the get restapi v10 account account ID extension extension ID answering rule params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleParams) WithAccountID(accountID string) *GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleParams {
	o.SetAccountID(accountID)
	return o
}

// SetAccountID adds the accountId to the get restapi v10 account account ID extension extension ID answering rule params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleParams) SetAccountID(accountID string) {
	o.AccountID = accountID
}

// WithExtensionID adds the extensionID to the get restapi v10 account account ID extension extension ID answering rule params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleParams) WithExtensionID(extensionID string) *GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleParams {
	o.SetExtensionID(extensionID)
	return o
}

// SetExtensionID adds the extensionId to the get restapi v10 account account ID extension extension ID answering rule params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleParams) SetExtensionID(extensionID string) {
	o.ExtensionID = extensionID
}

// WriteToRequest writes these params to a swagger request
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param accountId
	if err := r.SetPathParam("accountId", o.AccountID); err != nil {
		return err
	}

	// path param extensionId
	if err := r.SetPathParam("extensionId", o.ExtensionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
