package answering_rules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/grokify/go-ringcentral/models"
)

// GetRestapiV10AccountAccountIDExtensionExtensionIDGreetingGreetingIDReader is a Reader for the GetRestapiV10AccountAccountIDExtensionExtensionIDGreetingGreetingID structure.
type GetRestapiV10AccountAccountIDExtensionExtensionIDGreetingGreetingIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDGreetingGreetingIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {

	result := NewGetRestapiV10AccountAccountIDExtensionExtensionIDGreetingGreetingIDDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result

}

// NewGetRestapiV10AccountAccountIDExtensionExtensionIDGreetingGreetingIDDefault creates a GetRestapiV10AccountAccountIDExtensionExtensionIDGreetingGreetingIDDefault with default headers values
func NewGetRestapiV10AccountAccountIDExtensionExtensionIDGreetingGreetingIDDefault(code int) *GetRestapiV10AccountAccountIDExtensionExtensionIDGreetingGreetingIDDefault {
	return &GetRestapiV10AccountAccountIDExtensionExtensionIDGreetingGreetingIDDefault{
		_statusCode: code,
	}
}

/*GetRestapiV10AccountAccountIDExtensionExtensionIDGreetingGreetingIDDefault handles this case with default header values.

OK
*/
type GetRestapiV10AccountAccountIDExtensionExtensionIDGreetingGreetingIDDefault struct {
	_statusCode int

	Payload *models.CustomGreetingInfo
}

// Code gets the status code for the get restapi v10 account account ID extension extension ID greeting greeting ID default response
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDGreetingGreetingIDDefault) Code() int {
	return o._statusCode
}

func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDGreetingGreetingIDDefault) Error() string {
	return fmt.Sprintf("[GET /restapi/v1.0/account/{accountId}/extension/{extensionId}/greeting/{greetingId}][%d] GetRestapiV10AccountAccountIDExtensionExtensionIDGreetingGreetingID default  %+v", o._statusCode, o.Payload)
}

func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDGreetingGreetingIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CustomGreetingInfo)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
