package answering_rules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleAnsweringRuleIDParams creates a new GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleAnsweringRuleIDParams object
// with the default values initialized.
func NewGetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleAnsweringRuleIDParams() *GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleAnsweringRuleIDParams {
	var (
		accountIDDefault   = string("~")
		extensionIDDefault = string("~")
	)
	return &GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleAnsweringRuleIDParams{
		AccountID:   accountIDDefault,
		ExtensionID: extensionIDDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleAnsweringRuleIDParamsWithTimeout creates a new GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleAnsweringRuleIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleAnsweringRuleIDParamsWithTimeout(timeout time.Duration) *GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleAnsweringRuleIDParams {
	var (
		accountIDDefault   = string("~")
		extensionIDDefault = string("~")
	)
	return &GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleAnsweringRuleIDParams{
		AccountID:   accountIDDefault,
		ExtensionID: extensionIDDefault,

		timeout: timeout,
	}
}

// NewGetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleAnsweringRuleIDParamsWithContext creates a new GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleAnsweringRuleIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleAnsweringRuleIDParamsWithContext(ctx context.Context) *GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleAnsweringRuleIDParams {
	var (
		accountIdDefault   = string("~")
		extensionIdDefault = string("~")
	)
	return &GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleAnsweringRuleIDParams{
		AccountID:   accountIdDefault,
		ExtensionID: extensionIdDefault,

		Context: ctx,
	}
}

// NewGetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleAnsweringRuleIDParamsWithHTTPClient creates a new GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleAnsweringRuleIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleAnsweringRuleIDParamsWithHTTPClient(client *http.Client) *GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleAnsweringRuleIDParams {
	var (
		accountIdDefault   = string("~")
		extensionIdDefault = string("~")
	)
	return &GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleAnsweringRuleIDParams{
		AccountID:   accountIdDefault,
		ExtensionID: extensionIdDefault,
		HTTPClient:  client,
	}
}

/*GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleAnsweringRuleIDParams contains all the parameters to send to the API endpoint
for the get restapi v10 account account ID extension extension ID answering rule answering rule ID operation typically these are written to a http.Request
*/
type GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleAnsweringRuleIDParams struct {

	/*AccountID
	  Internal identifier of a RingCentral account or tilde (~) to indicate the account logged-in within the current session

	*/
	AccountID string
	/*AnsweringRuleID
	  Internal identifier of an answering rule. The value can be standard digital ID or specific ID - either business-hours-rule or after-hours-rule

	*/
	AnsweringRuleID string
	/*ExtensionID
	  Internal identifier of an extension or tilde (~) to indicate the extension assigned to the account logged-in within the current session

	*/
	ExtensionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get restapi v10 account account ID extension extension ID answering rule answering rule ID params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleAnsweringRuleIDParams) WithTimeout(timeout time.Duration) *GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleAnsweringRuleIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get restapi v10 account account ID extension extension ID answering rule answering rule ID params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleAnsweringRuleIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get restapi v10 account account ID extension extension ID answering rule answering rule ID params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleAnsweringRuleIDParams) WithContext(ctx context.Context) *GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleAnsweringRuleIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get restapi v10 account account ID extension extension ID answering rule answering rule ID params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleAnsweringRuleIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get restapi v10 account account ID extension extension ID answering rule answering rule ID params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleAnsweringRuleIDParams) WithHTTPClient(client *http.Client) *GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleAnsweringRuleIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get restapi v10 account account ID extension extension ID answering rule answering rule ID params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleAnsweringRuleIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccountID adds the accountID to the get restapi v10 account account ID extension extension ID answering rule answering rule ID params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleAnsweringRuleIDParams) WithAccountID(accountID string) *GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleAnsweringRuleIDParams {
	o.SetAccountID(accountID)
	return o
}

// SetAccountID adds the accountId to the get restapi v10 account account ID extension extension ID answering rule answering rule ID params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleAnsweringRuleIDParams) SetAccountID(accountID string) {
	o.AccountID = accountID
}

// WithAnsweringRuleID adds the answeringRuleID to the get restapi v10 account account ID extension extension ID answering rule answering rule ID params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleAnsweringRuleIDParams) WithAnsweringRuleID(answeringRuleID string) *GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleAnsweringRuleIDParams {
	o.SetAnsweringRuleID(answeringRuleID)
	return o
}

// SetAnsweringRuleID adds the answeringRuleId to the get restapi v10 account account ID extension extension ID answering rule answering rule ID params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleAnsweringRuleIDParams) SetAnsweringRuleID(answeringRuleID string) {
	o.AnsweringRuleID = answeringRuleID
}

// WithExtensionID adds the extensionID to the get restapi v10 account account ID extension extension ID answering rule answering rule ID params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleAnsweringRuleIDParams) WithExtensionID(extensionID string) *GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleAnsweringRuleIDParams {
	o.SetExtensionID(extensionID)
	return o
}

// SetExtensionID adds the extensionId to the get restapi v10 account account ID extension extension ID answering rule answering rule ID params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleAnsweringRuleIDParams) SetExtensionID(extensionID string) {
	o.ExtensionID = extensionID
}

// WriteToRequest writes these params to a swagger request
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDAnsweringRuleAnsweringRuleIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param accountId
	if err := r.SetPathParam("accountId", o.AccountID); err != nil {
		return err
	}

	// path param answeringRuleId
	if err := r.SetPathParam("answeringRuleId", o.AnsweringRuleID); err != nil {
		return err
	}

	// path param extensionId
	if err := r.SetPathParam("extensionId", o.ExtensionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
