package api_versions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/grokify/go-ringcentral/models"
)

// GetRestapiReader is a Reader for the GetRestapi structure.
type GetRestapiReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRestapiReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {

	result := NewGetRestapiDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result

}

// NewGetRestapiDefault creates a GetRestapiDefault with default headers values
func NewGetRestapiDefault(code int) *GetRestapiDefault {
	return &GetRestapiDefault{
		_statusCode: code,
	}
}

/*GetRestapiDefault handles this case with default header values.

OK
*/
type GetRestapiDefault struct {
	_statusCode int

	Payload *models.ServerInfo
}

// Code gets the status code for the get restapi default response
func (o *GetRestapiDefault) Code() int {
	return o._statusCode
}

func (o *GetRestapiDefault) Error() string {
	return fmt.Sprintf("[GET /restapi][%d] GetRestapi default  %+v", o._statusCode, o.Payload)
}

func (o *GetRestapiDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServerInfo)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
