package dictionary

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetRestapiV10DictionaryStateParams creates a new GetRestapiV10DictionaryStateParams object
// with the default values initialized.
func NewGetRestapiV10DictionaryStateParams() *GetRestapiV10DictionaryStateParams {
	var ()
	return &GetRestapiV10DictionaryStateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetRestapiV10DictionaryStateParamsWithTimeout creates a new GetRestapiV10DictionaryStateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetRestapiV10DictionaryStateParamsWithTimeout(timeout time.Duration) *GetRestapiV10DictionaryStateParams {
	var ()
	return &GetRestapiV10DictionaryStateParams{

		timeout: timeout,
	}
}

// NewGetRestapiV10DictionaryStateParamsWithContext creates a new GetRestapiV10DictionaryStateParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetRestapiV10DictionaryStateParamsWithContext(ctx context.Context) *GetRestapiV10DictionaryStateParams {
	var ()
	return &GetRestapiV10DictionaryStateParams{

		Context: ctx,
	}
}

// NewGetRestapiV10DictionaryStateParamsWithHTTPClient creates a new GetRestapiV10DictionaryStateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetRestapiV10DictionaryStateParamsWithHTTPClient(client *http.Client) *GetRestapiV10DictionaryStateParams {
	var ()
	return &GetRestapiV10DictionaryStateParams{
		HTTPClient: client,
	}
}

/*GetRestapiV10DictionaryStateParams contains all the parameters to send to the API endpoint
for the get restapi v10 dictionary state operation typically these are written to a http.Request
*/
type GetRestapiV10DictionaryStateParams struct {

	/*CountryID
	  Internal identifier of a country

	*/
	CountryID *int64
	/*Page
	  Indicates the page number to retrieve. Only positive number values are allowed. Default value is '1'.

	*/
	Page *int64
	/*PerPage
	  Indicates the page size (number of items). If not specified, the value is '100' by default

	*/
	PerPage *int64
	/*WithPhoneNumbers
	  If 'True', the list of states with phone numbers available for buying is returned. The default value is 'False'

	*/
	WithPhoneNumbers *bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get restapi v10 dictionary state params
func (o *GetRestapiV10DictionaryStateParams) WithTimeout(timeout time.Duration) *GetRestapiV10DictionaryStateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get restapi v10 dictionary state params
func (o *GetRestapiV10DictionaryStateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get restapi v10 dictionary state params
func (o *GetRestapiV10DictionaryStateParams) WithContext(ctx context.Context) *GetRestapiV10DictionaryStateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get restapi v10 dictionary state params
func (o *GetRestapiV10DictionaryStateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get restapi v10 dictionary state params
func (o *GetRestapiV10DictionaryStateParams) WithHTTPClient(client *http.Client) *GetRestapiV10DictionaryStateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get restapi v10 dictionary state params
func (o *GetRestapiV10DictionaryStateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCountryID adds the countryID to the get restapi v10 dictionary state params
func (o *GetRestapiV10DictionaryStateParams) WithCountryID(countryID *int64) *GetRestapiV10DictionaryStateParams {
	o.SetCountryID(countryID)
	return o
}

// SetCountryID adds the countryId to the get restapi v10 dictionary state params
func (o *GetRestapiV10DictionaryStateParams) SetCountryID(countryID *int64) {
	o.CountryID = countryID
}

// WithPage adds the page to the get restapi v10 dictionary state params
func (o *GetRestapiV10DictionaryStateParams) WithPage(page *int64) *GetRestapiV10DictionaryStateParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the get restapi v10 dictionary state params
func (o *GetRestapiV10DictionaryStateParams) SetPage(page *int64) {
	o.Page = page
}

// WithPerPage adds the perPage to the get restapi v10 dictionary state params
func (o *GetRestapiV10DictionaryStateParams) WithPerPage(perPage *int64) *GetRestapiV10DictionaryStateParams {
	o.SetPerPage(perPage)
	return o
}

// SetPerPage adds the perPage to the get restapi v10 dictionary state params
func (o *GetRestapiV10DictionaryStateParams) SetPerPage(perPage *int64) {
	o.PerPage = perPage
}

// WithWithPhoneNumbers adds the withPhoneNumbers to the get restapi v10 dictionary state params
func (o *GetRestapiV10DictionaryStateParams) WithWithPhoneNumbers(withPhoneNumbers *bool) *GetRestapiV10DictionaryStateParams {
	o.SetWithPhoneNumbers(withPhoneNumbers)
	return o
}

// SetWithPhoneNumbers adds the withPhoneNumbers to the get restapi v10 dictionary state params
func (o *GetRestapiV10DictionaryStateParams) SetWithPhoneNumbers(withPhoneNumbers *bool) {
	o.WithPhoneNumbers = withPhoneNumbers
}

// WriteToRequest writes these params to a swagger request
func (o *GetRestapiV10DictionaryStateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.CountryID != nil {

		// query param countryId
		var qrCountryID int64
		if o.CountryID != nil {
			qrCountryID = *o.CountryID
		}
		qCountryID := swag.FormatInt64(qrCountryID)
		if qCountryID != "" {
			if err := r.SetQueryParam("countryId", qCountryID); err != nil {
				return err
			}
		}

	}

	if o.Page != nil {

		// query param page
		var qrPage int64
		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt64(qrPage)
		if qPage != "" {
			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}

	}

	if o.PerPage != nil {

		// query param perPage
		var qrPerPage int64
		if o.PerPage != nil {
			qrPerPage = *o.PerPage
		}
		qPerPage := swag.FormatInt64(qrPerPage)
		if qPerPage != "" {
			if err := r.SetQueryParam("perPage", qPerPage); err != nil {
				return err
			}
		}

	}

	if o.WithPhoneNumbers != nil {

		// query param withPhoneNumbers
		var qrWithPhoneNumbers bool
		if o.WithPhoneNumbers != nil {
			qrWithPhoneNumbers = *o.WithPhoneNumbers
		}
		qWithPhoneNumbers := swag.FormatBool(qrWithPhoneNumbers)
		if qWithPhoneNumbers != "" {
			if err := r.SetQueryParam("withPhoneNumbers", qWithPhoneNumbers); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
