package dictionary

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/grokify/go-ringcentral/models"
)

// GetRestapiV10DictionaryCountryCountryIDReader is a Reader for the GetRestapiV10DictionaryCountryCountryID structure.
type GetRestapiV10DictionaryCountryCountryIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRestapiV10DictionaryCountryCountryIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {

	result := NewGetRestapiV10DictionaryCountryCountryIDDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result

}

// NewGetRestapiV10DictionaryCountryCountryIDDefault creates a GetRestapiV10DictionaryCountryCountryIDDefault with default headers values
func NewGetRestapiV10DictionaryCountryCountryIDDefault(code int) *GetRestapiV10DictionaryCountryCountryIDDefault {
	return &GetRestapiV10DictionaryCountryCountryIDDefault{
		_statusCode: code,
	}
}

/*GetRestapiV10DictionaryCountryCountryIDDefault handles this case with default header values.

OK
*/
type GetRestapiV10DictionaryCountryCountryIDDefault struct {
	_statusCode int

	Payload *models.FullCountryInfo
}

// Code gets the status code for the get restapi v10 dictionary country country ID default response
func (o *GetRestapiV10DictionaryCountryCountryIDDefault) Code() int {
	return o._statusCode
}

func (o *GetRestapiV10DictionaryCountryCountryIDDefault) Error() string {
	return fmt.Sprintf("[GET /restapi/v1.0/dictionary/country/{countryId}][%d] GetRestapiV10DictionaryCountryCountryID default  %+v", o._statusCode, o.Payload)
}

func (o *GetRestapiV10DictionaryCountryCountryIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.FullCountryInfo)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
