package call_log

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteRestapiV10AccountAccountIDExtensionExtensionIDCallLogReader is a Reader for the DeleteRestapiV10AccountAccountIDExtensionExtensionIDCallLog structure.
type DeleteRestapiV10AccountAccountIDExtensionExtensionIDCallLogReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteRestapiV10AccountAccountIDExtensionExtensionIDCallLogReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {

	result := NewDeleteRestapiV10AccountAccountIDExtensionExtensionIDCallLogDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result

}

// NewDeleteRestapiV10AccountAccountIDExtensionExtensionIDCallLogDefault creates a DeleteRestapiV10AccountAccountIDExtensionExtensionIDCallLogDefault with default headers values
func NewDeleteRestapiV10AccountAccountIDExtensionExtensionIDCallLogDefault(code int) *DeleteRestapiV10AccountAccountIDExtensionExtensionIDCallLogDefault {
	return &DeleteRestapiV10AccountAccountIDExtensionExtensionIDCallLogDefault{
		_statusCode: code,
	}
}

/*DeleteRestapiV10AccountAccountIDExtensionExtensionIDCallLogDefault handles this case with default header values.

OK
*/
type DeleteRestapiV10AccountAccountIDExtensionExtensionIDCallLogDefault struct {
	_statusCode int
}

// Code gets the status code for the delete restapi v10 account account ID extension extension ID call log default response
func (o *DeleteRestapiV10AccountAccountIDExtensionExtensionIDCallLogDefault) Code() int {
	return o._statusCode
}

func (o *DeleteRestapiV10AccountAccountIDExtensionExtensionIDCallLogDefault) Error() string {
	return fmt.Sprintf("[DELETE /restapi/v1.0/account/{accountId}/extension/{extensionId}/call-log][%d] DeleteRestapiV10AccountAccountIDExtensionExtensionIDCallLog default ", o._statusCode)
}

func (o *DeleteRestapiV10AccountAccountIDExtensionExtensionIDCallLogDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
