package call_log

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetRestapiV10AccountAccountIDRecordingRecordingIDContentParams creates a new GetRestapiV10AccountAccountIDRecordingRecordingIDContentParams object
// with the default values initialized.
func NewGetRestapiV10AccountAccountIDRecordingRecordingIDContentParams() *GetRestapiV10AccountAccountIDRecordingRecordingIDContentParams {
	var (
		accountIDDefault = string("~")
	)
	return &GetRestapiV10AccountAccountIDRecordingRecordingIDContentParams{
		AccountID: accountIDDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetRestapiV10AccountAccountIDRecordingRecordingIDContentParamsWithTimeout creates a new GetRestapiV10AccountAccountIDRecordingRecordingIDContentParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetRestapiV10AccountAccountIDRecordingRecordingIDContentParamsWithTimeout(timeout time.Duration) *GetRestapiV10AccountAccountIDRecordingRecordingIDContentParams {
	var (
		accountIDDefault = string("~")
	)
	return &GetRestapiV10AccountAccountIDRecordingRecordingIDContentParams{
		AccountID: accountIDDefault,

		timeout: timeout,
	}
}

// NewGetRestapiV10AccountAccountIDRecordingRecordingIDContentParamsWithContext creates a new GetRestapiV10AccountAccountIDRecordingRecordingIDContentParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetRestapiV10AccountAccountIDRecordingRecordingIDContentParamsWithContext(ctx context.Context) *GetRestapiV10AccountAccountIDRecordingRecordingIDContentParams {
	var (
		accountIdDefault = string("~")
	)
	return &GetRestapiV10AccountAccountIDRecordingRecordingIDContentParams{
		AccountID: accountIdDefault,

		Context: ctx,
	}
}

// NewGetRestapiV10AccountAccountIDRecordingRecordingIDContentParamsWithHTTPClient creates a new GetRestapiV10AccountAccountIDRecordingRecordingIDContentParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetRestapiV10AccountAccountIDRecordingRecordingIDContentParamsWithHTTPClient(client *http.Client) *GetRestapiV10AccountAccountIDRecordingRecordingIDContentParams {
	var (
		accountIdDefault = string("~")
	)
	return &GetRestapiV10AccountAccountIDRecordingRecordingIDContentParams{
		AccountID:  accountIdDefault,
		HTTPClient: client,
	}
}

/*GetRestapiV10AccountAccountIDRecordingRecordingIDContentParams contains all the parameters to send to the API endpoint
for the get restapi v10 account account ID recording recording ID content operation typically these are written to a http.Request
*/
type GetRestapiV10AccountAccountIDRecordingRecordingIDContentParams struct {

	/*AccountID
	  Internal identifier of a RingCentral account or tilde (~) to indicate the account logged-in within the current session

	*/
	AccountID string
	/*RecordingID
	  Internal identifier of recording (returned in Call Log)

	*/
	RecordingID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get restapi v10 account account ID recording recording ID content params
func (o *GetRestapiV10AccountAccountIDRecordingRecordingIDContentParams) WithTimeout(timeout time.Duration) *GetRestapiV10AccountAccountIDRecordingRecordingIDContentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get restapi v10 account account ID recording recording ID content params
func (o *GetRestapiV10AccountAccountIDRecordingRecordingIDContentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get restapi v10 account account ID recording recording ID content params
func (o *GetRestapiV10AccountAccountIDRecordingRecordingIDContentParams) WithContext(ctx context.Context) *GetRestapiV10AccountAccountIDRecordingRecordingIDContentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get restapi v10 account account ID recording recording ID content params
func (o *GetRestapiV10AccountAccountIDRecordingRecordingIDContentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get restapi v10 account account ID recording recording ID content params
func (o *GetRestapiV10AccountAccountIDRecordingRecordingIDContentParams) WithHTTPClient(client *http.Client) *GetRestapiV10AccountAccountIDRecordingRecordingIDContentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get restapi v10 account account ID recording recording ID content params
func (o *GetRestapiV10AccountAccountIDRecordingRecordingIDContentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccountID adds the accountID to the get restapi v10 account account ID recording recording ID content params
func (o *GetRestapiV10AccountAccountIDRecordingRecordingIDContentParams) WithAccountID(accountID string) *GetRestapiV10AccountAccountIDRecordingRecordingIDContentParams {
	o.SetAccountID(accountID)
	return o
}

// SetAccountID adds the accountId to the get restapi v10 account account ID recording recording ID content params
func (o *GetRestapiV10AccountAccountIDRecordingRecordingIDContentParams) SetAccountID(accountID string) {
	o.AccountID = accountID
}

// WithRecordingID adds the recordingID to the get restapi v10 account account ID recording recording ID content params
func (o *GetRestapiV10AccountAccountIDRecordingRecordingIDContentParams) WithRecordingID(recordingID string) *GetRestapiV10AccountAccountIDRecordingRecordingIDContentParams {
	o.SetRecordingID(recordingID)
	return o
}

// SetRecordingID adds the recordingId to the get restapi v10 account account ID recording recording ID content params
func (o *GetRestapiV10AccountAccountIDRecordingRecordingIDContentParams) SetRecordingID(recordingID string) {
	o.RecordingID = recordingID
}

// WriteToRequest writes these params to a swagger request
func (o *GetRestapiV10AccountAccountIDRecordingRecordingIDContentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param accountId
	if err := r.SetPathParam("accountId", o.AccountID); err != nil {
		return err
	}

	// path param recordingId
	if err := r.SetPathParam("recordingId", o.RecordingID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
