package call_log

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetRestapiV10AccountAccountIDExtensionExtensionIDCallLogCallLogIDParams creates a new GetRestapiV10AccountAccountIDExtensionExtensionIDCallLogCallLogIDParams object
// with the default values initialized.
func NewGetRestapiV10AccountAccountIDExtensionExtensionIDCallLogCallLogIDParams() *GetRestapiV10AccountAccountIDExtensionExtensionIDCallLogCallLogIDParams {
	var (
		accountIDDefault   = string("~")
		extensionIDDefault = string("~")
	)
	return &GetRestapiV10AccountAccountIDExtensionExtensionIDCallLogCallLogIDParams{
		AccountID:   accountIDDefault,
		ExtensionID: extensionIDDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetRestapiV10AccountAccountIDExtensionExtensionIDCallLogCallLogIDParamsWithTimeout creates a new GetRestapiV10AccountAccountIDExtensionExtensionIDCallLogCallLogIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetRestapiV10AccountAccountIDExtensionExtensionIDCallLogCallLogIDParamsWithTimeout(timeout time.Duration) *GetRestapiV10AccountAccountIDExtensionExtensionIDCallLogCallLogIDParams {
	var (
		accountIDDefault   = string("~")
		extensionIDDefault = string("~")
	)
	return &GetRestapiV10AccountAccountIDExtensionExtensionIDCallLogCallLogIDParams{
		AccountID:   accountIDDefault,
		ExtensionID: extensionIDDefault,

		timeout: timeout,
	}
}

// NewGetRestapiV10AccountAccountIDExtensionExtensionIDCallLogCallLogIDParamsWithContext creates a new GetRestapiV10AccountAccountIDExtensionExtensionIDCallLogCallLogIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetRestapiV10AccountAccountIDExtensionExtensionIDCallLogCallLogIDParamsWithContext(ctx context.Context) *GetRestapiV10AccountAccountIDExtensionExtensionIDCallLogCallLogIDParams {
	var (
		accountIdDefault   = string("~")
		extensionIdDefault = string("~")
	)
	return &GetRestapiV10AccountAccountIDExtensionExtensionIDCallLogCallLogIDParams{
		AccountID:   accountIdDefault,
		ExtensionID: extensionIdDefault,

		Context: ctx,
	}
}

// NewGetRestapiV10AccountAccountIDExtensionExtensionIDCallLogCallLogIDParamsWithHTTPClient creates a new GetRestapiV10AccountAccountIDExtensionExtensionIDCallLogCallLogIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetRestapiV10AccountAccountIDExtensionExtensionIDCallLogCallLogIDParamsWithHTTPClient(client *http.Client) *GetRestapiV10AccountAccountIDExtensionExtensionIDCallLogCallLogIDParams {
	var (
		accountIdDefault   = string("~")
		extensionIdDefault = string("~")
	)
	return &GetRestapiV10AccountAccountIDExtensionExtensionIDCallLogCallLogIDParams{
		AccountID:   accountIdDefault,
		ExtensionID: extensionIdDefault,
		HTTPClient:  client,
	}
}

/*GetRestapiV10AccountAccountIDExtensionExtensionIDCallLogCallLogIDParams contains all the parameters to send to the API endpoint
for the get restapi v10 account account ID extension extension ID call log call log ID operation typically these are written to a http.Request
*/
type GetRestapiV10AccountAccountIDExtensionExtensionIDCallLogCallLogIDParams struct {

	/*AccountID
	  Internal identifier of a RingCentral account or tilde (~) to indicate the account logged-in within the current session

	*/
	AccountID string
	/*CallLogID
	  Internal identifier of a call log record

	*/
	CallLogID string
	/*ExtensionID
	  Internal identifier of an extension or tilde (~) to indicate the extension assigned to the account logged-in within the current session

	*/
	ExtensionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get restapi v10 account account ID extension extension ID call log call log ID params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDCallLogCallLogIDParams) WithTimeout(timeout time.Duration) *GetRestapiV10AccountAccountIDExtensionExtensionIDCallLogCallLogIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get restapi v10 account account ID extension extension ID call log call log ID params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDCallLogCallLogIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get restapi v10 account account ID extension extension ID call log call log ID params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDCallLogCallLogIDParams) WithContext(ctx context.Context) *GetRestapiV10AccountAccountIDExtensionExtensionIDCallLogCallLogIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get restapi v10 account account ID extension extension ID call log call log ID params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDCallLogCallLogIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get restapi v10 account account ID extension extension ID call log call log ID params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDCallLogCallLogIDParams) WithHTTPClient(client *http.Client) *GetRestapiV10AccountAccountIDExtensionExtensionIDCallLogCallLogIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get restapi v10 account account ID extension extension ID call log call log ID params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDCallLogCallLogIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccountID adds the accountID to the get restapi v10 account account ID extension extension ID call log call log ID params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDCallLogCallLogIDParams) WithAccountID(accountID string) *GetRestapiV10AccountAccountIDExtensionExtensionIDCallLogCallLogIDParams {
	o.SetAccountID(accountID)
	return o
}

// SetAccountID adds the accountId to the get restapi v10 account account ID extension extension ID call log call log ID params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDCallLogCallLogIDParams) SetAccountID(accountID string) {
	o.AccountID = accountID
}

// WithCallLogID adds the callLogID to the get restapi v10 account account ID extension extension ID call log call log ID params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDCallLogCallLogIDParams) WithCallLogID(callLogID string) *GetRestapiV10AccountAccountIDExtensionExtensionIDCallLogCallLogIDParams {
	o.SetCallLogID(callLogID)
	return o
}

// SetCallLogID adds the callLogId to the get restapi v10 account account ID extension extension ID call log call log ID params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDCallLogCallLogIDParams) SetCallLogID(callLogID string) {
	o.CallLogID = callLogID
}

// WithExtensionID adds the extensionID to the get restapi v10 account account ID extension extension ID call log call log ID params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDCallLogCallLogIDParams) WithExtensionID(extensionID string) *GetRestapiV10AccountAccountIDExtensionExtensionIDCallLogCallLogIDParams {
	o.SetExtensionID(extensionID)
	return o
}

// SetExtensionID adds the extensionId to the get restapi v10 account account ID extension extension ID call log call log ID params
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDCallLogCallLogIDParams) SetExtensionID(extensionID string) {
	o.ExtensionID = extensionID
}

// WriteToRequest writes these params to a swagger request
func (o *GetRestapiV10AccountAccountIDExtensionExtensionIDCallLogCallLogIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param accountId
	if err := r.SetPathParam("accountId", o.AccountID); err != nil {
		return err
	}

	// path param callLogId
	if err := r.SetPathParam("callLogId", o.CallLogID); err != nil {
		return err
	}

	// path param extensionId
	if err := r.SetPathParam("extensionId", o.ExtensionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
