package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// DepartmentResponseExtensionInfo department response extension info
// swagger:model Department.Response.ExtensionInfo
type DepartmentResponseExtensionInfo struct {

	// Number of department extension
	ExtensionNumber string `json:"extensionNumber,omitempty"`

	// Internal identifier of an extension
	ID string `json:"id,omitempty"`

	// For Partner Applications Internal identifier of an extension created by partner. The RingCentral supports the mapping of accounts and stores the corresponding account ID/extension ID for each partner ID of a client application. In request URIs partner IDs are accepted instead of regular RingCentral native IDs as path parameters using pid = XXX clause. Though in response URIs contain the corresponding account IDs and extension IDs. In all request and response bodies these values are reflected via partnerId attributes of account and extension
	PartnerID string `json:"partnerId,omitempty"`

	// Canonical URI of an extension
	URI string `json:"uri,omitempty"`
}

// Validate validates this department response extension info
func (m *DepartmentResponseExtensionInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
