package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// ExtensionInfoRequestContactInfoRegionalSettingsFormattingLocale extension info request contact info regional settings formatting locale
// swagger:model ExtensionInfo.Request.ContactInfo.RegionalSettings.FormattingLocale
type ExtensionInfoRequestContactInfoRegionalSettingsFormattingLocale struct {

	// Internal identifier of a formatting language
	ID string `json:"id,omitempty"`
}

// Validate validates this extension info request contact info regional settings formatting locale
func (m *ExtensionInfoRequestContactInfoRegionalSettingsFormattingLocale) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
