package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// ExtensionServiceFeatureInfo extension service feature info
// swagger:model ExtensionServiceFeatureInfo
type ExtensionServiceFeatureInfo struct {

	// Feature status; shows feature availability for an extension
	Enabled bool `json:"enabled,omitempty"`

	// Feature name, see all available values in Service Feature List
	FeatureName string `json:"featureName,omitempty"`

	// Reason of limitation for a particular service feature. Returned only if the enabled parameter value is 'False', see Service Feature Limitations and Reasons. When retrieving service features for an extension, the reasons for the limitations, if any, are returned in response
	Reason string `json:"reason,omitempty"`
}

// Validate validates this extension service feature info
func (m *ExtensionServiceFeatureInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
