package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// ExtensionInfoRequestProvisionContactInfo extension info request provision contact info
// swagger:model ExtensionInfo.Request.Provision.ContactInfo
type ExtensionInfoRequestProvisionContactInfo struct {

	// Mandatory. Extension user contact email
	Email string `json:"email,omitempty"`

	// Mandatory. Extension user first name
	FirstName string `json:"firstName,omitempty"`

	// Mandatory. Extension user last name
	LastName string `json:"lastName,omitempty"`
}

// Validate validates this extension info request provision contact info
func (m *ExtensionInfoRequestProvisionContactInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
