package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// ImageURI image Uri
// swagger:model ImageUri
type ImageURI struct {

	// Link to an image.
	URI string `json:"uri,omitempty"`
}

// Validate validates this image Uri
func (m *ImageURI) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
