package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// LookUpPhoneNumberPhoneNumberInfo look up phone number phone number info
// swagger:model LookUpPhoneNumber.PhoneNumberInfo
type LookUpPhoneNumberPhoneNumberInfo struct {

	// Phone number formatted according to current brand's default country
	FormattedNumber string `json:"formattedNumber,omitempty"`

	// Phone number in E.164 format without a '+'
	PhoneNumber string `json:"phoneNumber,omitempty"`

	// The value is returned if the extendedSearch parameter is true. '10' is the closest match
	Rank int64 `json:"rank,omitempty"`

	// Vanity pattern for this number. Returned only when vanity search option is requested. Vanity pattern corresponds to request parameters nxx plus line or numberPattern
	VanityPattern string `json:"vanityPattern,omitempty"`
}

// Validate validates this look up phone number phone number info
func (m *LookUpPhoneNumberPhoneNumberInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
