package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// ParsePhoneNumberCountryInfo parse phone number country info
// swagger:model ParsePhoneNumber.CountryInfo
type ParsePhoneNumberCountryInfo struct {

	// Country calling code defined by ITU-T recommendations E.123 and E.164, see Calling Codes
	CallingCode string `json:"callingCode,omitempty"`

	// Emergency calling feature availability/emergency address requirement indicator
	EmergencyCalling bool `json:"emergencyCalling,omitempty"`

	// Internal identifier of a country
	ID string `json:"id,omitempty"`

	// Country code according to the ISO standard, see ISO 3166
	IsoCode string `json:"isoCode,omitempty"`

	// Official name of a country
	Name string `json:"name,omitempty"`

	// Canonical URI of a country
	URI string `json:"uri,omitempty"`
}

// Validate validates this parse phone number country info
func (m *ParsePhoneNumberCountryInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
