package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// PermissionInfo permission info
// swagger:model PermissionInfo
type PermissionInfo struct {

	// Specifies if a permission is enabled or not
	Enabled bool `json:"enabled,omitempty"`
}

// Validate validates this permission info
func (m *PermissionInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
