package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// PresenceLineEventExtensionInfo presence line event extension info
// swagger:model PresenceLineEvent.ExtensionInfo
type PresenceLineEventExtensionInfo struct {

	// Internal identifier of the extension
	ID string `json:"id,omitempty"`
}

// Validate validates this presence line event extension info
func (m *PresenceLineEventExtensionInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
