package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// RingOutRequestTo ring out request to
// swagger:model RingOut.Request.To
type RingOutRequestTo struct {

	// Phone number in E.164 format
	PhoneNumber string `json:"phoneNumber,omitempty"`
}

// Validate validates this ring out request to
func (m *RingOutRequestTo) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
