package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// RuleInfo rule info
// swagger:model RuleInfo
type RuleInfo struct {

	// Forwarding number (or group) data
	ForwardingNumbers []*RuleInfoForwardingNumberInfo `json:"forwardingNumbers"`

	// Forwarding number (or group) ordinal
	Index int64 `json:"index,omitempty"`

	// Number of rings for a forwarding number (or group)
	RingCount int64 `json:"ringCount,omitempty"`
}

// Validate validates this rule info
func (m *RuleInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateForwardingNumbers(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RuleInfo) validateForwardingNumbers(formats strfmt.Registry) error {

	if swag.IsZero(m.ForwardingNumbers) { // not required
		return nil
	}

	for i := 0; i < len(m.ForwardingNumbers); i++ {

		if swag.IsZero(m.ForwardingNumbers[i]) { // not required
			continue
		}

		if m.ForwardingNumbers[i] != nil {

			if err := m.ForwardingNumbers[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("forwardingNumbers" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}
