package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// StatusInfo status info
// swagger:model StatusInfo
type StatusInfo struct {

	// A free-form user comment, describing the status change reason
	Comment string `json:"comment,omitempty"`

	// Type of suspension
	Reason string `json:"reason,omitempty"`
}

// Validate validates this status info
func (m *StatusInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateReason(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var statusInfoTypeReasonPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["Voluntarily","Involuntarily"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		statusInfoTypeReasonPropEnum = append(statusInfoTypeReasonPropEnum, v)
	}
}

const (
	// StatusInfoReasonVoluntarily captures enum value "Voluntarily"
	StatusInfoReasonVoluntarily string = "Voluntarily"
	// StatusInfoReasonInvoluntarily captures enum value "Involuntarily"
	StatusInfoReasonInvoluntarily string = "Involuntarily"
)

// prop value enum
func (m *StatusInfo) validateReasonEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, statusInfoTypeReasonPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *StatusInfo) validateReason(formats strfmt.Registry) error {

	if swag.IsZero(m.Reason) { // not required
		return nil
	}

	// value enum
	if err := m.validateReasonEnum("reason", "body", m.Reason); err != nil {
		return err
	}

	return nil
}
