package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// TargetServicePlanInfo target service plan info
// swagger:model TargetServicePlanInfo
type TargetServicePlanInfo struct {

	// Internal identifier of a target service plan
	ID string `json:"id,omitempty"`

	// Name of a target service plan
	Name string `json:"name,omitempty"`
}

// Validate validates this target service plan info
func (m *TargetServicePlanInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
